// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: control.proto
// Protobuf C++ Version: 7.34.1

#include "control.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace aether {
namespace proto {

inline constexpr RouteDecision::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        stream_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        selected_node_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        decision_timestamp_us_{::uint64_t{0u}},
        confidence_score_{0} {}

template <typename>
constexpr RouteDecision::RouteDecision(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RouteDecision_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct RouteDecisionDefaultTypeInternal {
  constexpr RouteDecisionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RouteDecisionDefaultTypeInternal() {}
  union {
    RouteDecision _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RouteDecisionDefaultTypeInternal _RouteDecision_default_instance_;

inline constexpr NodeTelemetry::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        node_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        cpu_load_percent_{0u},
        bandwidth_usage_mbps_{0},
        latency_ms_{0},
        packet_drop_count_{0u},
        health_score_{0} {}

template <typename>
constexpr NodeTelemetry::NodeTelemetry(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(NodeTelemetry_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct NodeTelemetryDefaultTypeInternal {
  constexpr NodeTelemetryDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NodeTelemetryDefaultTypeInternal() {}
  union {
    NodeTelemetry _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NodeTelemetryDefaultTypeInternal _NodeTelemetry_default_instance_;
}  // namespace proto
}  // namespace aether
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_control_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_control_2eproto = nullptr;
const ::uint32_t
    TableStruct_control_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::aether::proto::NodeTelemetry, _impl_._has_bits_),
        9, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::aether::proto::NodeTelemetry, _impl_.node_id_),
        PROTOBUF_FIELD_OFFSET(::aether::proto::NodeTelemetry, _impl_.cpu_load_percent_),
        PROTOBUF_FIELD_OFFSET(::aether::proto::NodeTelemetry, _impl_.bandwidth_usage_mbps_),
        PROTOBUF_FIELD_OFFSET(::aether::proto::NodeTelemetry, _impl_.latency_ms_),
        PROTOBUF_FIELD_OFFSET(::aether::proto::NodeTelemetry, _impl_.packet_drop_count_),
        PROTOBUF_FIELD_OFFSET(::aether::proto::NodeTelemetry, _impl_.health_score_),
        0,
        1,
        2,
        3,
        4,
        5,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::aether::proto::RouteDecision, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::aether::proto::RouteDecision, _impl_.stream_id_),
        PROTOBUF_FIELD_OFFSET(::aether::proto::RouteDecision, _impl_.selected_node_id_),
        PROTOBUF_FIELD_OFFSET(::aether::proto::RouteDecision, _impl_.confidence_score_),
        PROTOBUF_FIELD_OFFSET(::aether::proto::RouteDecision, _impl_.decision_timestamp_us_),
        0,
        1,
        3,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::aether::proto::NodeTelemetry)},
        {15, sizeof(::aether::proto::RouteDecision)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::aether::proto::_NodeTelemetry_default_instance_._instance,
    &::aether::proto::_RouteDecision_default_instance_._instance,
};
const char descriptor_table_protodef_control_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\rcontrol.proto\022\014aether.proto\"\235\001\n\rNodeTe"
    "lemetry\022\017\n\007node_id\030\001 \001(\t\022\030\n\020cpu_load_per"
    "cent\030\002 \001(\r\022\034\n\024bandwidth_usage_mbps\030\003 \001(\002"
    "\022\022\n\nlatency_ms\030\004 \001(\002\022\031\n\021packet_drop_coun"
    "t\030\005 \001(\r\022\024\n\014health_score\030\006 \001(\002\"u\n\rRouteDe"
    "cision\022\021\n\tstream_id\030\001 \001(\t\022\030\n\020selected_no"
    "de_id\030\002 \001(\t\022\030\n\020confidence_score\030\003 \001(\002\022\035\n"
    "\025decision_timestamp_us\030\004 \001(\004b\006proto3"
};
static ::absl::once_flag descriptor_table_control_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_control_2eproto = {
    false,
    false,
    316,
    descriptor_table_protodef_control_2eproto,
    "control.proto",
    &descriptor_table_control_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_control_2eproto::offsets,
    file_level_enum_descriptors_control_2eproto,
    file_level_service_descriptors_control_2eproto,
};
namespace aether {
namespace proto {
// ===================================================================

class NodeTelemetry::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<NodeTelemetry>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NodeTelemetry, _impl_._has_bits_);
};

NodeTelemetry::NodeTelemetry(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NodeTelemetry_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:aether.proto.NodeTelemetry)
}
PROTOBUF_NDEBUG_INLINE NodeTelemetry::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::aether::proto::NodeTelemetry& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        node_id_(arena, from.node_id_) {}

NodeTelemetry::NodeTelemetry(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const NodeTelemetry& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NodeTelemetry_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NodeTelemetry* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, cpu_load_percent_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, cpu_load_percent_),
           offsetof(Impl_, health_score_) -
               offsetof(Impl_, cpu_load_percent_) +
               sizeof(Impl_::health_score_));

  // @@protoc_insertion_point(copy_constructor:aether.proto.NodeTelemetry)
}
PROTOBUF_NDEBUG_INLINE NodeTelemetry::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        node_id_(arena) {}

inline void NodeTelemetry::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, cpu_load_percent_),
           0,
           offsetof(Impl_, health_score_) -
               offsetof(Impl_, cpu_load_percent_) +
               sizeof(Impl_::health_score_));
}
NodeTelemetry::~NodeTelemetry() {
  // @@protoc_insertion_point(destructor:aether.proto.NodeTelemetry)
  SharedDtor(*this);
}
inline void NodeTelemetry::SharedDtor(MessageLite& self) {
  NodeTelemetry& this_ = static_cast<NodeTelemetry&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.node_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL NodeTelemetry::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NodeTelemetry(arena);
}
constexpr auto NodeTelemetry::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(NodeTelemetry),
                                            alignof(NodeTelemetry));
}
constexpr auto NodeTelemetry::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_NodeTelemetry_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &NodeTelemetry::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<NodeTelemetry>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NodeTelemetry::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<NodeTelemetry>(), &NodeTelemetry::ByteSizeLong,
              &NodeTelemetry::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NodeTelemetry, _impl_._cached_size_),
          false,
      },
      &NodeTelemetry::kDescriptorMethods,
      &descriptor_table_control_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull NodeTelemetry_class_data_ =
        NodeTelemetry::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NodeTelemetry::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NodeTelemetry_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(NodeTelemetry_class_data_.tc_table);
  return NodeTelemetry_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 42, 2>
NodeTelemetry::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NodeTelemetry, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    NodeTelemetry_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aether::proto::NodeTelemetry>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string node_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(NodeTelemetry, _impl_.node_id_)}},
    // uint32 cpu_load_percent = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NodeTelemetry, _impl_.cpu_load_percent_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(NodeTelemetry, _impl_.cpu_load_percent_)}},
    // float bandwidth_usage_mbps = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 2, 0,
      PROTOBUF_FIELD_OFFSET(NodeTelemetry, _impl_.bandwidth_usage_mbps_)}},
    // float latency_ms = 4;
    {::_pbi::TcParser::FastF32S1,
     {37, 3, 0,
      PROTOBUF_FIELD_OFFSET(NodeTelemetry, _impl_.latency_ms_)}},
    // uint32 packet_drop_count = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NodeTelemetry, _impl_.packet_drop_count_), 4>(),
     {40, 4, 0,
      PROTOBUF_FIELD_OFFSET(NodeTelemetry, _impl_.packet_drop_count_)}},
    // float health_score = 6;
    {::_pbi::TcParser::FastF32S1,
     {53, 5, 0,
      PROTOBUF_FIELD_OFFSET(NodeTelemetry, _impl_.health_score_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string node_id = 1;
    {PROTOBUF_FIELD_OFFSET(NodeTelemetry, _impl_.node_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 cpu_load_percent = 2;
    {PROTOBUF_FIELD_OFFSET(NodeTelemetry, _impl_.cpu_load_percent_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // float bandwidth_usage_mbps = 3;
    {PROTOBUF_FIELD_OFFSET(NodeTelemetry, _impl_.bandwidth_usage_mbps_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // float latency_ms = 4;
    {PROTOBUF_FIELD_OFFSET(NodeTelemetry, _impl_.latency_ms_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // uint32 packet_drop_count = 5;
    {PROTOBUF_FIELD_OFFSET(NodeTelemetry, _impl_.packet_drop_count_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // float health_score = 6;
    {PROTOBUF_FIELD_OFFSET(NodeTelemetry, _impl_.health_score_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
    "\32\7\0\0\0\0\0\0"
    "aether.proto.NodeTelemetry"
    "node_id"
  }},
};
PROTOBUF_NOINLINE void NodeTelemetry::Clear() {
// @@protoc_insertion_point(message_clear_start:aether.proto.NodeTelemetry)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.node_id_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000003eU)) {
    ::memset(&_impl_.cpu_load_percent_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.health_score_) -
        reinterpret_cast<char*>(&_impl_.cpu_load_percent_)) + sizeof(_impl_.health_score_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL NodeTelemetry::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const NodeTelemetry& this_ = static_cast<const NodeTelemetry&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL NodeTelemetry::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const NodeTelemetry& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:aether.proto.NodeTelemetry)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string node_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_node_id().empty()) {
      const ::std::string& _s = this_._internal_node_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "aether.proto.NodeTelemetry.node_id");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // uint32 cpu_load_percent = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_cpu_load_percent() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          2, this_._internal_cpu_load_percent(), target);
    }
  }

  // float bandwidth_usage_mbps = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_bandwidth_usage_mbps()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          3, this_._internal_bandwidth_usage_mbps(), target);
    }
  }

  // float latency_ms = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_latency_ms()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          4, this_._internal_latency_ms(), target);
    }
  }

  // uint32 packet_drop_count = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_packet_drop_count() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          5, this_._internal_packet_drop_count(), target);
    }
  }

  // float health_score = 6;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_health_score()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          6, this_._internal_health_score(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aether.proto.NodeTelemetry)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t NodeTelemetry::ByteSizeLong(const MessageLite& base) {
  const NodeTelemetry& this_ = static_cast<const NodeTelemetry&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t NodeTelemetry::ByteSizeLong() const {
  const NodeTelemetry& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:aether.proto.NodeTelemetry)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    // string node_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_node_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_node_id());
      }
    }
    // uint32 cpu_load_percent = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_cpu_load_percent() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_cpu_load_percent());
      }
    }
    // float bandwidth_usage_mbps = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_bandwidth_usage_mbps()) != 0) {
        total_size += 5;
      }
    }
    // float latency_ms = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_latency_ms()) != 0) {
        total_size += 5;
      }
    }
    // uint32 packet_drop_count = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_packet_drop_count() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_packet_drop_count());
      }
    }
    // float health_score = 6;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_health_score()) != 0) {
        total_size += 5;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void NodeTelemetry::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<NodeTelemetry*>(&to_msg);
  auto& from = static_cast<const NodeTelemetry&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:aether.proto.NodeTelemetry)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_node_id().empty()) {
        _this->_internal_set_node_id(from._internal_node_id());
      } else {
        if (_this->_impl_.node_id_.IsDefault()) {
          _this->_internal_set_node_id("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_cpu_load_percent() != 0) {
        _this->_impl_.cpu_load_percent_ = from._impl_.cpu_load_percent_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_bandwidth_usage_mbps()) != 0) {
        _this->_impl_.bandwidth_usage_mbps_ = from._impl_.bandwidth_usage_mbps_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_latency_ms()) != 0) {
        _this->_impl_.latency_ms_ = from._impl_.latency_ms_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_packet_drop_count() != 0) {
        _this->_impl_.packet_drop_count_ = from._impl_.packet_drop_count_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_health_score()) != 0) {
        _this->_impl_.health_score_ = from._impl_.health_score_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void NodeTelemetry::CopyFrom(const NodeTelemetry& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:aether.proto.NodeTelemetry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NodeTelemetry::InternalSwap(NodeTelemetry* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.node_id_, &other->_impl_.node_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NodeTelemetry, _impl_.health_score_)
      + sizeof(NodeTelemetry::_impl_.health_score_)
      - PROTOBUF_FIELD_OFFSET(NodeTelemetry, _impl_.cpu_load_percent_)>(
          reinterpret_cast<char*>(&_impl_.cpu_load_percent_),
          reinterpret_cast<char*>(&other->_impl_.cpu_load_percent_));
}

::google::protobuf::Metadata NodeTelemetry::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RouteDecision::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RouteDecision>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RouteDecision, _impl_._has_bits_);
};

RouteDecision::RouteDecision(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RouteDecision_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:aether.proto.RouteDecision)
}
PROTOBUF_NDEBUG_INLINE RouteDecision::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::aether::proto::RouteDecision& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        stream_id_(arena, from.stream_id_),
        selected_node_id_(arena, from.selected_node_id_) {}

RouteDecision::RouteDecision(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RouteDecision& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RouteDecision_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RouteDecision* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, decision_timestamp_us_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, decision_timestamp_us_),
           offsetof(Impl_, confidence_score_) -
               offsetof(Impl_, decision_timestamp_us_) +
               sizeof(Impl_::confidence_score_));

  // @@protoc_insertion_point(copy_constructor:aether.proto.RouteDecision)
}
PROTOBUF_NDEBUG_INLINE RouteDecision::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        stream_id_(arena),
        selected_node_id_(arena) {}

inline void RouteDecision::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, decision_timestamp_us_),
           0,
           offsetof(Impl_, confidence_score_) -
               offsetof(Impl_, decision_timestamp_us_) +
               sizeof(Impl_::confidence_score_));
}
RouteDecision::~RouteDecision() {
  // @@protoc_insertion_point(destructor:aether.proto.RouteDecision)
  SharedDtor(*this);
}
inline void RouteDecision::SharedDtor(MessageLite& self) {
  RouteDecision& this_ = static_cast<RouteDecision&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.stream_id_.Destroy();
  this_._impl_.selected_node_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RouteDecision::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RouteDecision(arena);
}
constexpr auto RouteDecision::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RouteDecision),
                                            alignof(RouteDecision));
}
constexpr auto RouteDecision::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RouteDecision_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &RouteDecision::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RouteDecision>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RouteDecision::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RouteDecision>(), &RouteDecision::ByteSizeLong,
              &RouteDecision::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RouteDecision, _impl_._cached_size_),
          false,
      },
      &RouteDecision::kDescriptorMethods,
      &descriptor_table_control_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RouteDecision_class_data_ =
        RouteDecision::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RouteDecision::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RouteDecision_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RouteDecision_class_data_.tc_table);
  return RouteDecision_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 60, 2>
RouteDecision::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RouteDecision, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RouteDecision_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aether::proto::RouteDecision>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 decision_timestamp_us = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(RouteDecision, _impl_.decision_timestamp_us_), 2>(),
     {32, 2, 0,
      PROTOBUF_FIELD_OFFSET(RouteDecision, _impl_.decision_timestamp_us_)}},
    // string stream_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(RouteDecision, _impl_.stream_id_)}},
    // string selected_node_id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(RouteDecision, _impl_.selected_node_id_)}},
    // float confidence_score = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 3, 0,
      PROTOBUF_FIELD_OFFSET(RouteDecision, _impl_.confidence_score_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string stream_id = 1;
    {PROTOBUF_FIELD_OFFSET(RouteDecision, _impl_.stream_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string selected_node_id = 2;
    {PROTOBUF_FIELD_OFFSET(RouteDecision, _impl_.selected_node_id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // float confidence_score = 3;
    {PROTOBUF_FIELD_OFFSET(RouteDecision, _impl_.confidence_score_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // uint64 decision_timestamp_us = 4;
    {PROTOBUF_FIELD_OFFSET(RouteDecision, _impl_.decision_timestamp_us_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
    "\32\11\20\0\0\0\0\0"
    "aether.proto.RouteDecision"
    "stream_id"
    "selected_node_id"
  }},
};
PROTOBUF_NOINLINE void RouteDecision::Clear() {
// @@protoc_insertion_point(message_clear_start:aether.proto.RouteDecision)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.stream_id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.selected_node_id_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000000cU)) {
    ::memset(&_impl_.decision_timestamp_us_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.confidence_score_) -
        reinterpret_cast<char*>(&_impl_.decision_timestamp_us_)) + sizeof(_impl_.confidence_score_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RouteDecision::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RouteDecision& this_ = static_cast<const RouteDecision&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RouteDecision::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RouteDecision& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:aether.proto.RouteDecision)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string stream_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_stream_id().empty()) {
      const ::std::string& _s = this_._internal_stream_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "aether.proto.RouteDecision.stream_id");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string selected_node_id = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_selected_node_id().empty()) {
      const ::std::string& _s = this_._internal_selected_node_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "aether.proto.RouteDecision.selected_node_id");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // float confidence_score = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_confidence_score()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          3, this_._internal_confidence_score(), target);
    }
  }

  // uint64 decision_timestamp_us = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_decision_timestamp_us() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          4, this_._internal_decision_timestamp_us(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aether.proto.RouteDecision)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RouteDecision::ByteSizeLong(const MessageLite& base) {
  const RouteDecision& this_ = static_cast<const RouteDecision&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RouteDecision::ByteSizeLong() const {
  const RouteDecision& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:aether.proto.RouteDecision)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // string stream_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_stream_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_stream_id());
      }
    }
    // string selected_node_id = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_selected_node_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_selected_node_id());
      }
    }
    // uint64 decision_timestamp_us = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_decision_timestamp_us() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_decision_timestamp_us());
      }
    }
    // float confidence_score = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_confidence_score()) != 0) {
        total_size += 5;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RouteDecision::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<RouteDecision*>(&to_msg);
  auto& from = static_cast<const RouteDecision&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:aether.proto.RouteDecision)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_stream_id().empty()) {
        _this->_internal_set_stream_id(from._internal_stream_id());
      } else {
        if (_this->_impl_.stream_id_.IsDefault()) {
          _this->_internal_set_stream_id("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_selected_node_id().empty()) {
        _this->_internal_set_selected_node_id(from._internal_selected_node_id());
      } else {
        if (_this->_impl_.selected_node_id_.IsDefault()) {
          _this->_internal_set_selected_node_id("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_decision_timestamp_us() != 0) {
        _this->_impl_.decision_timestamp_us_ = from._impl_.decision_timestamp_us_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_confidence_score()) != 0) {
        _this->_impl_.confidence_score_ = from._impl_.confidence_score_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RouteDecision::CopyFrom(const RouteDecision& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:aether.proto.RouteDecision)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RouteDecision::InternalSwap(RouteDecision* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.stream_id_, &other->_impl_.stream_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.selected_node_id_, &other->_impl_.selected_node_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RouteDecision, _impl_.confidence_score_)
      + sizeof(RouteDecision::_impl_.confidence_score_)
      - PROTOBUF_FIELD_OFFSET(RouteDecision, _impl_.decision_timestamp_us_)>(
          reinterpret_cast<char*>(&_impl_.decision_timestamp_us_),
          reinterpret_cast<char*>(&other->_impl_.decision_timestamp_us_));
}

::google::protobuf::Metadata RouteDecision::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace aether
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_control_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
