// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: control.proto
// Protobuf C++ Version: 7.34.1

#ifndef control_2eproto_2epb_2eh
#define control_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_control_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_control_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_control_2eproto;
}  // extern "C"
namespace aether {
namespace proto {
class NodeTelemetry;
struct NodeTelemetryDefaultTypeInternal;
extern NodeTelemetryDefaultTypeInternal _NodeTelemetry_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull NodeTelemetry_class_data_;
class RouteDecision;
struct RouteDecisionDefaultTypeInternal;
extern RouteDecisionDefaultTypeInternal _RouteDecision_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RouteDecision_class_data_;
}  // namespace proto
}  // namespace aether
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace aether {
namespace proto {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED RouteDecision final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:aether.proto.RouteDecision) */ {
 public:
  inline RouteDecision() : RouteDecision(nullptr) {}
  ~RouteDecision() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RouteDecision* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RouteDecision));
  }
#endif

  template <typename = void>
  explicit constexpr RouteDecision(::google::protobuf::internal::ConstantInitialized);

  inline RouteDecision(const RouteDecision& from) : RouteDecision(nullptr, from) {}
  inline RouteDecision(RouteDecision&& from) noexcept
      : RouteDecision(nullptr, ::std::move(from)) {}
  inline RouteDecision& operator=(const RouteDecision& from) {
    CopyFrom(from);
    return *this;
  }
  inline RouteDecision& operator=(RouteDecision&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const RouteDecision& default_instance() {
    return *reinterpret_cast<const RouteDecision*>(
        &_RouteDecision_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(RouteDecision& a, RouteDecision& b) { a.Swap(&b); }
  inline void Swap(RouteDecision* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RouteDecision* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] RouteDecision* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RouteDecision>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RouteDecision& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RouteDecision& from) { RouteDecision::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RouteDecision* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "aether.proto.RouteDecision"; }

  explicit RouteDecision(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RouteDecision(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RouteDecision& from);
  RouteDecision(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RouteDecision&& from) noexcept
      : RouteDecision(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStreamIdFieldNumber = 1,
    kSelectedNodeIdFieldNumber = 2,
    kDecisionTimestampUsFieldNumber = 4,
    kConfidenceScoreFieldNumber = 3,
  };
  // string stream_id = 1;
  void clear_stream_id() ;
  [[nodiscard]] const ::std::string& stream_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_stream_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_stream_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_stream_id();
  void set_allocated_stream_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_stream_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_stream_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_stream_id();

  public:
  // string selected_node_id = 2;
  void clear_selected_node_id() ;
  [[nodiscard]] const ::std::string& selected_node_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_selected_node_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_selected_node_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_selected_node_id();
  void set_allocated_selected_node_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_selected_node_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_selected_node_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_selected_node_id();

  public:
  // uint64 decision_timestamp_us = 4;
  void clear_decision_timestamp_us() ;
  [[nodiscard]] ::uint64_t decision_timestamp_us() const;
  void set_decision_timestamp_us(::uint64_t value);

  private:
  ::uint64_t _internal_decision_timestamp_us() const;
  void _internal_set_decision_timestamp_us(::uint64_t value);

  public:
  // float confidence_score = 3;
  void clear_confidence_score() ;
  [[nodiscard]] float confidence_score() const;
  void set_confidence_score(float value);

  private:
  float _internal_confidence_score() const;
  void _internal_set_confidence_score(float value);

  public:
  // @@protoc_insertion_point(class_scope:aether.proto.RouteDecision)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 60,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RouteDecision& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr stream_id_;
    ::google::protobuf::internal::ArenaStringPtr selected_node_id_;
    ::uint64_t decision_timestamp_us_;
    float confidence_score_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_control_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RouteDecision_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED NodeTelemetry final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:aether.proto.NodeTelemetry) */ {
 public:
  inline NodeTelemetry() : NodeTelemetry(nullptr) {}
  ~NodeTelemetry() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(NodeTelemetry* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(NodeTelemetry));
  }
#endif

  template <typename = void>
  explicit constexpr NodeTelemetry(::google::protobuf::internal::ConstantInitialized);

  inline NodeTelemetry(const NodeTelemetry& from) : NodeTelemetry(nullptr, from) {}
  inline NodeTelemetry(NodeTelemetry&& from) noexcept
      : NodeTelemetry(nullptr, ::std::move(from)) {}
  inline NodeTelemetry& operator=(const NodeTelemetry& from) {
    CopyFrom(from);
    return *this;
  }
  inline NodeTelemetry& operator=(NodeTelemetry&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const NodeTelemetry& default_instance() {
    return *reinterpret_cast<const NodeTelemetry*>(
        &_NodeTelemetry_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(NodeTelemetry& a, NodeTelemetry& b) { a.Swap(&b); }
  inline void Swap(NodeTelemetry* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NodeTelemetry* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] NodeTelemetry* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<NodeTelemetry>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const NodeTelemetry& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const NodeTelemetry& from) { NodeTelemetry::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(NodeTelemetry* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "aether.proto.NodeTelemetry"; }

  explicit NodeTelemetry(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  NodeTelemetry(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const NodeTelemetry& from);
  NodeTelemetry(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, NodeTelemetry&& from) noexcept
      : NodeTelemetry(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNodeIdFieldNumber = 1,
    kCpuLoadPercentFieldNumber = 2,
    kBandwidthUsageMbpsFieldNumber = 3,
    kLatencyMsFieldNumber = 4,
    kPacketDropCountFieldNumber = 5,
    kHealthScoreFieldNumber = 6,
  };
  // string node_id = 1;
  void clear_node_id() ;
  [[nodiscard]] const ::std::string& node_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_node_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_node_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_node_id();
  void set_allocated_node_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_node_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_node_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_node_id();

  public:
  // uint32 cpu_load_percent = 2;
  void clear_cpu_load_percent() ;
  [[nodiscard]] ::uint32_t cpu_load_percent() const;
  void set_cpu_load_percent(::uint32_t value);

  private:
  ::uint32_t _internal_cpu_load_percent() const;
  void _internal_set_cpu_load_percent(::uint32_t value);

  public:
  // float bandwidth_usage_mbps = 3;
  void clear_bandwidth_usage_mbps() ;
  [[nodiscard]] float bandwidth_usage_mbps() const;
  void set_bandwidth_usage_mbps(float value);

  private:
  float _internal_bandwidth_usage_mbps() const;
  void _internal_set_bandwidth_usage_mbps(float value);

  public:
  // float latency_ms = 4;
  void clear_latency_ms() ;
  [[nodiscard]] float latency_ms() const;
  void set_latency_ms(float value);

  private:
  float _internal_latency_ms() const;
  void _internal_set_latency_ms(float value);

  public:
  // uint32 packet_drop_count = 5;
  void clear_packet_drop_count() ;
  [[nodiscard]] ::uint32_t packet_drop_count() const;
  void set_packet_drop_count(::uint32_t value);

  private:
  ::uint32_t _internal_packet_drop_count() const;
  void _internal_set_packet_drop_count(::uint32_t value);

  public:
  // float health_score = 6;
  void clear_health_score() ;
  [[nodiscard]] float health_score() const;
  void set_health_score(float value);

  private:
  float _internal_health_score() const;
  void _internal_set_health_score(float value);

  public:
  // @@protoc_insertion_point(class_scope:aether.proto.NodeTelemetry)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6,
                                   0, 42,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const NodeTelemetry& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr node_id_;
    ::uint32_t cpu_load_percent_;
    float bandwidth_usage_mbps_;
    float latency_ms_;
    ::uint32_t packet_drop_count_;
    float health_score_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_control_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull NodeTelemetry_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// NodeTelemetry

// string node_id = 1;
inline void NodeTelemetry::clear_node_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.node_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& NodeTelemetry::node_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aether.proto.NodeTelemetry.node_id)
  return _internal_node_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void NodeTelemetry::set_node_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.node_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:aether.proto.NodeTelemetry.node_id)
}
inline ::std::string* PROTOBUF_NONNULL NodeTelemetry::mutable_node_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_node_id();
  // @@protoc_insertion_point(field_mutable:aether.proto.NodeTelemetry.node_id)
  return _s;
}
inline const ::std::string& NodeTelemetry::_internal_node_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.node_id_.Get();
}
inline void NodeTelemetry::_internal_set_node_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.node_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL NodeTelemetry::_internal_mutable_node_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.node_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE NodeTelemetry::release_node_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:aether.proto.NodeTelemetry.node_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.node_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.node_id_.Set("", GetArena());
  }
  return released;
}
inline void NodeTelemetry::set_allocated_node_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.node_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.node_id_.IsDefault()) {
    _impl_.node_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:aether.proto.NodeTelemetry.node_id)
}

// uint32 cpu_load_percent = 2;
inline void NodeTelemetry::clear_cpu_load_percent() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cpu_load_percent_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t NodeTelemetry::cpu_load_percent() const {
  // @@protoc_insertion_point(field_get:aether.proto.NodeTelemetry.cpu_load_percent)
  return _internal_cpu_load_percent();
}
inline void NodeTelemetry::set_cpu_load_percent(::uint32_t value) {
  _internal_set_cpu_load_percent(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:aether.proto.NodeTelemetry.cpu_load_percent)
}
inline ::uint32_t NodeTelemetry::_internal_cpu_load_percent() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cpu_load_percent_;
}
inline void NodeTelemetry::_internal_set_cpu_load_percent(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cpu_load_percent_ = value;
}

// float bandwidth_usage_mbps = 3;
inline void NodeTelemetry::clear_bandwidth_usage_mbps() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bandwidth_usage_mbps_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline float NodeTelemetry::bandwidth_usage_mbps() const {
  // @@protoc_insertion_point(field_get:aether.proto.NodeTelemetry.bandwidth_usage_mbps)
  return _internal_bandwidth_usage_mbps();
}
inline void NodeTelemetry::set_bandwidth_usage_mbps(float value) {
  _internal_set_bandwidth_usage_mbps(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:aether.proto.NodeTelemetry.bandwidth_usage_mbps)
}
inline float NodeTelemetry::_internal_bandwidth_usage_mbps() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bandwidth_usage_mbps_;
}
inline void NodeTelemetry::_internal_set_bandwidth_usage_mbps(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bandwidth_usage_mbps_ = value;
}

// float latency_ms = 4;
inline void NodeTelemetry::clear_latency_ms() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.latency_ms_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline float NodeTelemetry::latency_ms() const {
  // @@protoc_insertion_point(field_get:aether.proto.NodeTelemetry.latency_ms)
  return _internal_latency_ms();
}
inline void NodeTelemetry::set_latency_ms(float value) {
  _internal_set_latency_ms(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:aether.proto.NodeTelemetry.latency_ms)
}
inline float NodeTelemetry::_internal_latency_ms() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.latency_ms_;
}
inline void NodeTelemetry::_internal_set_latency_ms(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.latency_ms_ = value;
}

// uint32 packet_drop_count = 5;
inline void NodeTelemetry::clear_packet_drop_count() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.packet_drop_count_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint32_t NodeTelemetry::packet_drop_count() const {
  // @@protoc_insertion_point(field_get:aether.proto.NodeTelemetry.packet_drop_count)
  return _internal_packet_drop_count();
}
inline void NodeTelemetry::set_packet_drop_count(::uint32_t value) {
  _internal_set_packet_drop_count(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:aether.proto.NodeTelemetry.packet_drop_count)
}
inline ::uint32_t NodeTelemetry::_internal_packet_drop_count() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.packet_drop_count_;
}
inline void NodeTelemetry::_internal_set_packet_drop_count(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.packet_drop_count_ = value;
}

// float health_score = 6;
inline void NodeTelemetry::clear_health_score() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.health_score_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline float NodeTelemetry::health_score() const {
  // @@protoc_insertion_point(field_get:aether.proto.NodeTelemetry.health_score)
  return _internal_health_score();
}
inline void NodeTelemetry::set_health_score(float value) {
  _internal_set_health_score(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:aether.proto.NodeTelemetry.health_score)
}
inline float NodeTelemetry::_internal_health_score() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.health_score_;
}
inline void NodeTelemetry::_internal_set_health_score(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.health_score_ = value;
}

// -------------------------------------------------------------------

// RouteDecision

// string stream_id = 1;
inline void RouteDecision::clear_stream_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stream_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& RouteDecision::stream_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aether.proto.RouteDecision.stream_id)
  return _internal_stream_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RouteDecision::set_stream_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.stream_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:aether.proto.RouteDecision.stream_id)
}
inline ::std::string* PROTOBUF_NONNULL RouteDecision::mutable_stream_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_stream_id();
  // @@protoc_insertion_point(field_mutable:aether.proto.RouteDecision.stream_id)
  return _s;
}
inline const ::std::string& RouteDecision::_internal_stream_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.stream_id_.Get();
}
inline void RouteDecision::_internal_set_stream_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stream_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RouteDecision::_internal_mutable_stream_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.stream_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RouteDecision::release_stream_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:aether.proto.RouteDecision.stream_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.stream_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.stream_id_.Set("", GetArena());
  }
  return released;
}
inline void RouteDecision::set_allocated_stream_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.stream_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.stream_id_.IsDefault()) {
    _impl_.stream_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:aether.proto.RouteDecision.stream_id)
}

// string selected_node_id = 2;
inline void RouteDecision::clear_selected_node_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.selected_node_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& RouteDecision::selected_node_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aether.proto.RouteDecision.selected_node_id)
  return _internal_selected_node_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RouteDecision::set_selected_node_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.selected_node_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:aether.proto.RouteDecision.selected_node_id)
}
inline ::std::string* PROTOBUF_NONNULL RouteDecision::mutable_selected_node_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_selected_node_id();
  // @@protoc_insertion_point(field_mutable:aether.proto.RouteDecision.selected_node_id)
  return _s;
}
inline const ::std::string& RouteDecision::_internal_selected_node_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.selected_node_id_.Get();
}
inline void RouteDecision::_internal_set_selected_node_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.selected_node_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RouteDecision::_internal_mutable_selected_node_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.selected_node_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RouteDecision::release_selected_node_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:aether.proto.RouteDecision.selected_node_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.selected_node_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.selected_node_id_.Set("", GetArena());
  }
  return released;
}
inline void RouteDecision::set_allocated_selected_node_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.selected_node_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.selected_node_id_.IsDefault()) {
    _impl_.selected_node_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:aether.proto.RouteDecision.selected_node_id)
}

// float confidence_score = 3;
inline void RouteDecision::clear_confidence_score() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.confidence_score_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline float RouteDecision::confidence_score() const {
  // @@protoc_insertion_point(field_get:aether.proto.RouteDecision.confidence_score)
  return _internal_confidence_score();
}
inline void RouteDecision::set_confidence_score(float value) {
  _internal_set_confidence_score(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:aether.proto.RouteDecision.confidence_score)
}
inline float RouteDecision::_internal_confidence_score() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.confidence_score_;
}
inline void RouteDecision::_internal_set_confidence_score(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.confidence_score_ = value;
}

// uint64 decision_timestamp_us = 4;
inline void RouteDecision::clear_decision_timestamp_us() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.decision_timestamp_us_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint64_t RouteDecision::decision_timestamp_us() const {
  // @@protoc_insertion_point(field_get:aether.proto.RouteDecision.decision_timestamp_us)
  return _internal_decision_timestamp_us();
}
inline void RouteDecision::set_decision_timestamp_us(::uint64_t value) {
  _internal_set_decision_timestamp_us(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:aether.proto.RouteDecision.decision_timestamp_us)
}
inline ::uint64_t RouteDecision::_internal_decision_timestamp_us() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.decision_timestamp_us_;
}
inline void RouteDecision::_internal_set_decision_timestamp_us(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.decision_timestamp_us_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace aether


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // control_2eproto_2epb_2eh
