// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: packet.proto
// Protobuf C++ Version: 7.34.1

#ifndef packet_2eproto_2epb_2eh
#define packet_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_packet_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_packet_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_packet_2eproto;
}  // extern "C"
namespace aether {
namespace proto {
class AetherPacket;
struct AetherPacketDefaultTypeInternal;
extern AetherPacketDefaultTypeInternal _AetherPacket_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull AetherPacket_class_data_;
}  // namespace proto
}  // namespace aether
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace aether {
namespace proto {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED AetherPacket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:aether.proto.AetherPacket) */ {
 public:
  inline AetherPacket() : AetherPacket(nullptr) {}
  ~AetherPacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AetherPacket* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AetherPacket));
  }
#endif

  template <typename = void>
  explicit constexpr AetherPacket(::google::protobuf::internal::ConstantInitialized);

  inline AetherPacket(const AetherPacket& from) : AetherPacket(nullptr, from) {}
  inline AetherPacket(AetherPacket&& from) noexcept
      : AetherPacket(nullptr, ::std::move(from)) {}
  inline AetherPacket& operator=(const AetherPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline AetherPacket& operator=(AetherPacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const AetherPacket& default_instance() {
    return *reinterpret_cast<const AetherPacket*>(
        &_AetherPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(AetherPacket& a, AetherPacket& b) { a.Swap(&b); }
  inline void Swap(AetherPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AetherPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] AetherPacket* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AetherPacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AetherPacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AetherPacket& from) { AetherPacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AetherPacket* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "aether.proto.AetherPacket"; }

  explicit AetherPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AetherPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AetherPacket& from);
  AetherPacket(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AetherPacket&& from) noexcept
      : AetherPacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSourceIdFieldNumber = 1,
    kTargetIdFieldNumber = 2,
    kCipherIvFieldNumber = 6,
    kPayloadFieldNumber = 7,
    kSequenceNumFieldNumber = 3,
    kTimestampUsFieldNumber = 4,
    kTrafficClassFieldNumber = 5,
  };
  // string source_id = 1;
  void clear_source_id() ;
  [[nodiscard]] const ::std::string& source_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_source_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_source_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_source_id();
  void set_allocated_source_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_source_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_source_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_source_id();

  public:
  // string target_id = 2;
  void clear_target_id() ;
  [[nodiscard]] const ::std::string& target_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_target_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_target_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_target_id();
  void set_allocated_target_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_target_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_target_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_target_id();

  public:
  // bytes cipher_iv = 6;
  void clear_cipher_iv() ;
  [[nodiscard]] const ::std::string& cipher_iv() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_cipher_iv(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_cipher_iv();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_cipher_iv();
  void set_allocated_cipher_iv(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_cipher_iv() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_cipher_iv(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_cipher_iv();

  public:
  // bytes payload = 7;
  void clear_payload() ;
  [[nodiscard]] const ::std::string& payload() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_payload(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_payload();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_payload();
  void set_allocated_payload(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_payload() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_payload(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_payload();

  public:
  // uint64 sequence_num = 3;
  void clear_sequence_num() ;
  [[nodiscard]] ::uint64_t sequence_num() const;
  void set_sequence_num(::uint64_t value);

  private:
  ::uint64_t _internal_sequence_num() const;
  void _internal_set_sequence_num(::uint64_t value);

  public:
  // uint64 timestamp_us = 4;
  void clear_timestamp_us() ;
  [[nodiscard]] ::uint64_t timestamp_us() const;
  void set_timestamp_us(::uint64_t value);

  private:
  ::uint64_t _internal_timestamp_us() const;
  void _internal_set_timestamp_us(::uint64_t value);

  public:
  // uint32 traffic_class = 5;
  void clear_traffic_class() ;
  [[nodiscard]] ::uint32_t traffic_class() const;
  void set_traffic_class(::uint32_t value);

  private:
  ::uint32_t _internal_traffic_class() const;
  void _internal_set_traffic_class(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:aether.proto.AetherPacket)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 7,
                                   0, 52,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AetherPacket& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr source_id_;
    ::google::protobuf::internal::ArenaStringPtr target_id_;
    ::google::protobuf::internal::ArenaStringPtr cipher_iv_;
    ::google::protobuf::internal::ArenaStringPtr payload_;
    ::uint64_t sequence_num_;
    ::uint64_t timestamp_us_;
    ::uint32_t traffic_class_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packet_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull AetherPacket_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AetherPacket

// string source_id = 1;
inline void AetherPacket::clear_source_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& AetherPacket::source_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aether.proto.AetherPacket.source_id)
  return _internal_source_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void AetherPacket::set_source_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.source_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:aether.proto.AetherPacket.source_id)
}
inline ::std::string* PROTOBUF_NONNULL AetherPacket::mutable_source_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_source_id();
  // @@protoc_insertion_point(field_mutable:aether.proto.AetherPacket.source_id)
  return _s;
}
inline const ::std::string& AetherPacket::_internal_source_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.source_id_.Get();
}
inline void AetherPacket::_internal_set_source_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL AetherPacket::_internal_mutable_source_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.source_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE AetherPacket::release_source_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:aether.proto.AetherPacket.source_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.source_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.source_id_.Set("", GetArena());
  }
  return released;
}
inline void AetherPacket::set_allocated_source_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.source_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.source_id_.IsDefault()) {
    _impl_.source_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:aether.proto.AetherPacket.source_id)
}

// string target_id = 2;
inline void AetherPacket::clear_target_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& AetherPacket::target_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aether.proto.AetherPacket.target_id)
  return _internal_target_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void AetherPacket::set_target_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.target_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:aether.proto.AetherPacket.target_id)
}
inline ::std::string* PROTOBUF_NONNULL AetherPacket::mutable_target_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_target_id();
  // @@protoc_insertion_point(field_mutable:aether.proto.AetherPacket.target_id)
  return _s;
}
inline const ::std::string& AetherPacket::_internal_target_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.target_id_.Get();
}
inline void AetherPacket::_internal_set_target_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL AetherPacket::_internal_mutable_target_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.target_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE AetherPacket::release_target_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:aether.proto.AetherPacket.target_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.target_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.target_id_.Set("", GetArena());
  }
  return released;
}
inline void AetherPacket::set_allocated_target_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.target_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.target_id_.IsDefault()) {
    _impl_.target_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:aether.proto.AetherPacket.target_id)
}

// uint64 sequence_num = 3;
inline void AetherPacket::clear_sequence_num() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequence_num_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint64_t AetherPacket::sequence_num() const {
  // @@protoc_insertion_point(field_get:aether.proto.AetherPacket.sequence_num)
  return _internal_sequence_num();
}
inline void AetherPacket::set_sequence_num(::uint64_t value) {
  _internal_set_sequence_num(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:aether.proto.AetherPacket.sequence_num)
}
inline ::uint64_t AetherPacket::_internal_sequence_num() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sequence_num_;
}
inline void AetherPacket::_internal_set_sequence_num(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequence_num_ = value;
}

// uint64 timestamp_us = 4;
inline void AetherPacket::clear_timestamp_us() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_us_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::uint64_t AetherPacket::timestamp_us() const {
  // @@protoc_insertion_point(field_get:aether.proto.AetherPacket.timestamp_us)
  return _internal_timestamp_us();
}
inline void AetherPacket::set_timestamp_us(::uint64_t value) {
  _internal_set_timestamp_us(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:aether.proto.AetherPacket.timestamp_us)
}
inline ::uint64_t AetherPacket::_internal_timestamp_us() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_us_;
}
inline void AetherPacket::_internal_set_timestamp_us(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_us_ = value;
}

// uint32 traffic_class = 5;
inline void AetherPacket::clear_traffic_class() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.traffic_class_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::uint32_t AetherPacket::traffic_class() const {
  // @@protoc_insertion_point(field_get:aether.proto.AetherPacket.traffic_class)
  return _internal_traffic_class();
}
inline void AetherPacket::set_traffic_class(::uint32_t value) {
  _internal_set_traffic_class(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:aether.proto.AetherPacket.traffic_class)
}
inline ::uint32_t AetherPacket::_internal_traffic_class() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.traffic_class_;
}
inline void AetherPacket::_internal_set_traffic_class(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.traffic_class_ = value;
}

// bytes cipher_iv = 6;
inline void AetherPacket::clear_cipher_iv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cipher_iv_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& AetherPacket::cipher_iv() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aether.proto.AetherPacket.cipher_iv)
  return _internal_cipher_iv();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void AetherPacket::set_cipher_iv(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.cipher_iv_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:aether.proto.AetherPacket.cipher_iv)
}
inline ::std::string* PROTOBUF_NONNULL AetherPacket::mutable_cipher_iv()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_cipher_iv();
  // @@protoc_insertion_point(field_mutable:aether.proto.AetherPacket.cipher_iv)
  return _s;
}
inline const ::std::string& AetherPacket::_internal_cipher_iv() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cipher_iv_.Get();
}
inline void AetherPacket::_internal_set_cipher_iv(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cipher_iv_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL AetherPacket::_internal_mutable_cipher_iv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.cipher_iv_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE AetherPacket::release_cipher_iv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:aether.proto.AetherPacket.cipher_iv)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.cipher_iv_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.cipher_iv_.Set("", GetArena());
  }
  return released;
}
inline void AetherPacket::set_allocated_cipher_iv(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.cipher_iv_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.cipher_iv_.IsDefault()) {
    _impl_.cipher_iv_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:aether.proto.AetherPacket.cipher_iv)
}

// bytes payload = 7;
inline void AetherPacket::clear_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.payload_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& AetherPacket::payload() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aether.proto.AetherPacket.payload)
  return _internal_payload();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void AetherPacket::set_payload(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.payload_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:aether.proto.AetherPacket.payload)
}
inline ::std::string* PROTOBUF_NONNULL AetherPacket::mutable_payload()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_payload();
  // @@protoc_insertion_point(field_mutable:aether.proto.AetherPacket.payload)
  return _s;
}
inline const ::std::string& AetherPacket::_internal_payload() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.payload_.Get();
}
inline void AetherPacket::_internal_set_payload(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.payload_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL AetherPacket::_internal_mutable_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.payload_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE AetherPacket::release_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:aether.proto.AetherPacket.payload)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.payload_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.payload_.Set("", GetArena());
  }
  return released;
}
inline void AetherPacket::set_allocated_payload(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.payload_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.payload_.IsDefault()) {
    _impl_.payload_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:aether.proto.AetherPacket.payload)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace aether


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // packet_2eproto_2epb_2eh
