// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: packet.proto
// Protobuf C++ Version: 7.34.1

#include "packet.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace aether {
namespace proto {

inline constexpr AetherPacket::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        source_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        target_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        cipher_iv_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        sequence_num_{::uint64_t{0u}},
        timestamp_us_{::uint64_t{0u}},
        traffic_class_{0u} {}

template <typename>
constexpr AetherPacket::AetherPacket(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(AetherPacket_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct AetherPacketDefaultTypeInternal {
  constexpr AetherPacketDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AetherPacketDefaultTypeInternal() {}
  union {
    AetherPacket _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AetherPacketDefaultTypeInternal _AetherPacket_default_instance_;
}  // namespace proto
}  // namespace aether
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_packet_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_packet_2eproto = nullptr;
const ::uint32_t
    TableStruct_packet_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::aether::proto::AetherPacket, _impl_._has_bits_),
        10, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::aether::proto::AetherPacket, _impl_.source_id_),
        PROTOBUF_FIELD_OFFSET(::aether::proto::AetherPacket, _impl_.target_id_),
        PROTOBUF_FIELD_OFFSET(::aether::proto::AetherPacket, _impl_.sequence_num_),
        PROTOBUF_FIELD_OFFSET(::aether::proto::AetherPacket, _impl_.timestamp_us_),
        PROTOBUF_FIELD_OFFSET(::aether::proto::AetherPacket, _impl_.traffic_class_),
        PROTOBUF_FIELD_OFFSET(::aether::proto::AetherPacket, _impl_.cipher_iv_),
        PROTOBUF_FIELD_OFFSET(::aether::proto::AetherPacket, _impl_.payload_),
        0,
        1,
        4,
        5,
        6,
        2,
        3,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::aether::proto::AetherPacket)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::aether::proto::_AetherPacket_default_instance_._instance,
};
const char descriptor_table_protodef_packet_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014packet.proto\022\014aether.proto\"\233\001\n\014AetherP"
    "acket\022\021\n\tsource_id\030\001 \001(\t\022\021\n\ttarget_id\030\002 "
    "\001(\t\022\024\n\014sequence_num\030\003 \001(\004\022\024\n\014timestamp_u"
    "s\030\004 \001(\004\022\025\n\rtraffic_class\030\005 \001(\r\022\021\n\tcipher"
    "_iv\030\006 \001(\014\022\017\n\007payload\030\007 \001(\014b\006proto3"
};
static ::absl::once_flag descriptor_table_packet_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_packet_2eproto = {
    false,
    false,
    194,
    descriptor_table_protodef_packet_2eproto,
    "packet.proto",
    &descriptor_table_packet_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_packet_2eproto::offsets,
    file_level_enum_descriptors_packet_2eproto,
    file_level_service_descriptors_packet_2eproto,
};
namespace aether {
namespace proto {
// ===================================================================

class AetherPacket::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<AetherPacket>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AetherPacket, _impl_._has_bits_);
};

AetherPacket::AetherPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AetherPacket_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:aether.proto.AetherPacket)
}
PROTOBUF_NDEBUG_INLINE AetherPacket::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::aether::proto::AetherPacket& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        source_id_(arena, from.source_id_),
        target_id_(arena, from.target_id_),
        cipher_iv_(arena, from.cipher_iv_),
        payload_(arena, from.payload_) {}

AetherPacket::AetherPacket(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const AetherPacket& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AetherPacket_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AetherPacket* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, sequence_num_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, sequence_num_),
           offsetof(Impl_, traffic_class_) -
               offsetof(Impl_, sequence_num_) +
               sizeof(Impl_::traffic_class_));

  // @@protoc_insertion_point(copy_constructor:aether.proto.AetherPacket)
}
PROTOBUF_NDEBUG_INLINE AetherPacket::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        source_id_(arena),
        target_id_(arena),
        cipher_iv_(arena),
        payload_(arena) {}

inline void AetherPacket::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, sequence_num_),
           0,
           offsetof(Impl_, traffic_class_) -
               offsetof(Impl_, sequence_num_) +
               sizeof(Impl_::traffic_class_));
}
AetherPacket::~AetherPacket() {
  // @@protoc_insertion_point(destructor:aether.proto.AetherPacket)
  SharedDtor(*this);
}
inline void AetherPacket::SharedDtor(MessageLite& self) {
  AetherPacket& this_ = static_cast<AetherPacket&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.source_id_.Destroy();
  this_._impl_.target_id_.Destroy();
  this_._impl_.cipher_iv_.Destroy();
  this_._impl_.payload_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL AetherPacket::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) AetherPacket(arena);
}
constexpr auto AetherPacket::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(AetherPacket),
                                            alignof(AetherPacket));
}
constexpr auto AetherPacket::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_AetherPacket_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &AetherPacket::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<AetherPacket>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &AetherPacket::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<AetherPacket>(), &AetherPacket::ByteSizeLong,
              &AetherPacket::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(AetherPacket, _impl_._cached_size_),
          false,
      },
      &AetherPacket::kDescriptorMethods,
      &descriptor_table_packet_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull AetherPacket_class_data_ =
        AetherPacket::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
AetherPacket::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&AetherPacket_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(AetherPacket_class_data_.tc_table);
  return AetherPacket_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 0, 52, 2>
AetherPacket::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AetherPacket, _impl_._has_bits_),
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    AetherPacket_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aether::proto::AetherPacket>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string source_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(AetherPacket, _impl_.source_id_)}},
    // string target_id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(AetherPacket, _impl_.target_id_)}},
    // uint64 sequence_num = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(AetherPacket, _impl_.sequence_num_), 4>(),
     {24, 4, 0,
      PROTOBUF_FIELD_OFFSET(AetherPacket, _impl_.sequence_num_)}},
    // uint64 timestamp_us = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(AetherPacket, _impl_.timestamp_us_), 5>(),
     {32, 5, 0,
      PROTOBUF_FIELD_OFFSET(AetherPacket, _impl_.timestamp_us_)}},
    // uint32 traffic_class = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AetherPacket, _impl_.traffic_class_), 6>(),
     {40, 6, 0,
      PROTOBUF_FIELD_OFFSET(AetherPacket, _impl_.traffic_class_)}},
    // bytes cipher_iv = 6;
    {::_pbi::TcParser::FastBS1,
     {50, 2, 0,
      PROTOBUF_FIELD_OFFSET(AetherPacket, _impl_.cipher_iv_)}},
    // bytes payload = 7;
    {::_pbi::TcParser::FastBS1,
     {58, 3, 0,
      PROTOBUF_FIELD_OFFSET(AetherPacket, _impl_.payload_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string source_id = 1;
    {PROTOBUF_FIELD_OFFSET(AetherPacket, _impl_.source_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string target_id = 2;
    {PROTOBUF_FIELD_OFFSET(AetherPacket, _impl_.target_id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint64 sequence_num = 3;
    {PROTOBUF_FIELD_OFFSET(AetherPacket, _impl_.sequence_num_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint64 timestamp_us = 4;
    {PROTOBUF_FIELD_OFFSET(AetherPacket, _impl_.timestamp_us_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint32 traffic_class = 5;
    {PROTOBUF_FIELD_OFFSET(AetherPacket, _impl_.traffic_class_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // bytes cipher_iv = 6;
    {PROTOBUF_FIELD_OFFSET(AetherPacket, _impl_.cipher_iv_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes payload = 7;
    {PROTOBUF_FIELD_OFFSET(AetherPacket, _impl_.payload_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\11\11\0\0\0\0\0"
    "aether.proto.AetherPacket"
    "source_id"
    "target_id"
  }},
};
PROTOBUF_NOINLINE void AetherPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:aether.proto.AetherPacket)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.source_id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.target_id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.cipher_iv_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.payload_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000070U)) {
    ::memset(&_impl_.sequence_num_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.traffic_class_) -
        reinterpret_cast<char*>(&_impl_.sequence_num_)) + sizeof(_impl_.traffic_class_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL AetherPacket::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const AetherPacket& this_ = static_cast<const AetherPacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL AetherPacket::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const AetherPacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:aether.proto.AetherPacket)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string source_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_source_id().empty()) {
      const ::std::string& _s = this_._internal_source_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "aether.proto.AetherPacket.source_id");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string target_id = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_target_id().empty()) {
      const ::std::string& _s = this_._internal_target_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "aether.proto.AetherPacket.target_id");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // uint64 sequence_num = 3;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_sequence_num() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          3, this_._internal_sequence_num(), target);
    }
  }

  // uint64 timestamp_us = 4;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_timestamp_us() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          4, this_._internal_timestamp_us(), target);
    }
  }

  // uint32 traffic_class = 5;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_traffic_class() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          5, this_._internal_traffic_class(), target);
    }
  }

  // bytes cipher_iv = 6;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_cipher_iv().empty()) {
      const ::std::string& _s = this_._internal_cipher_iv();
      target = stream->WriteBytesMaybeAliased(6, _s, target);
    }
  }

  // bytes payload = 7;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (!this_._internal_payload().empty()) {
      const ::std::string& _s = this_._internal_payload();
      target = stream->WriteBytesMaybeAliased(7, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aether.proto.AetherPacket)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t AetherPacket::ByteSizeLong(const MessageLite& base) {
  const AetherPacket& this_ = static_cast<const AetherPacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t AetherPacket::ByteSizeLong() const {
  const AetherPacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:aether.proto.AetherPacket)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    // string source_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_source_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_source_id());
      }
    }
    // string target_id = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_target_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_target_id());
      }
    }
    // bytes cipher_iv = 6;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_cipher_iv().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_cipher_iv());
      }
    }
    // bytes payload = 7;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!this_._internal_payload().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_payload());
      }
    }
    // uint64 sequence_num = 3;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_sequence_num() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_sequence_num());
      }
    }
    // uint64 timestamp_us = 4;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_timestamp_us() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_timestamp_us());
      }
    }
    // uint32 traffic_class = 5;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_traffic_class() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_traffic_class());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void AetherPacket::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<AetherPacket*>(&to_msg);
  auto& from = static_cast<const AetherPacket&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:aether.proto.AetherPacket)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_source_id().empty()) {
        _this->_internal_set_source_id(from._internal_source_id());
      } else {
        if (_this->_impl_.source_id_.IsDefault()) {
          _this->_internal_set_source_id("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_target_id().empty()) {
        _this->_internal_set_target_id(from._internal_target_id());
      } else {
        if (_this->_impl_.target_id_.IsDefault()) {
          _this->_internal_set_target_id("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_cipher_iv().empty()) {
        _this->_internal_set_cipher_iv(from._internal_cipher_iv());
      } else {
        if (_this->_impl_.cipher_iv_.IsDefault()) {
          _this->_internal_set_cipher_iv("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!from._internal_payload().empty()) {
        _this->_internal_set_payload(from._internal_payload());
      } else {
        if (_this->_impl_.payload_.IsDefault()) {
          _this->_internal_set_payload("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_sequence_num() != 0) {
        _this->_impl_.sequence_num_ = from._impl_.sequence_num_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_timestamp_us() != 0) {
        _this->_impl_.timestamp_us_ = from._impl_.timestamp_us_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_traffic_class() != 0) {
        _this->_impl_.traffic_class_ = from._impl_.traffic_class_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void AetherPacket::CopyFrom(const AetherPacket& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:aether.proto.AetherPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AetherPacket::InternalSwap(AetherPacket* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.source_id_, &other->_impl_.source_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.target_id_, &other->_impl_.target_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.cipher_iv_, &other->_impl_.cipher_iv_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.payload_, &other->_impl_.payload_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AetherPacket, _impl_.traffic_class_)
      + sizeof(AetherPacket::_impl_.traffic_class_)
      - PROTOBUF_FIELD_OFFSET(AetherPacket, _impl_.sequence_num_)>(
          reinterpret_cast<char*>(&_impl_.sequence_num_),
          reinterpret_cast<char*>(&other->_impl_.sequence_num_));
}

::google::protobuf::Metadata AetherPacket::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace aether
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_packet_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
