// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: control.proto
// Protobuf Java Version: 4.34.1

package aether.proto;

@com.google.protobuf.Generated
public final class Control extends com.google.protobuf.GeneratedFile {
  private Control() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "Control");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NodeTelemetryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:aether.proto.NodeTelemetry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string node_id = 1;</code>
     * @return The nodeId.
     */
    java.lang.String getNodeId();
    /**
     * <code>string node_id = 1;</code>
     * @return The bytes for nodeId.
     */
    com.google.protobuf.ByteString
        getNodeIdBytes();

    /**
     * <pre>
     * Load of the proxy node out of 100
     * </pre>
     *
     * <code>uint32 cpu_load_percent = 2;</code>
     * @return The cpuLoadPercent.
     */
    int getCpuLoadPercent();

    /**
     * <pre>
     * Total throughput currently being handled by node in Mbps
     * </pre>
     *
     * <code>float bandwidth_usage_mbps = 3;</code>
     * @return The bandwidthUsageMbps.
     */
    float getBandwidthUsageMbps();

    /**
     * <pre>
     * Local detected connection ping to backbone
     * </pre>
     *
     * <code>float latency_ms = 4;</code>
     * @return The latencyMs.
     */
    float getLatencyMs();

    /**
     * <pre>
     * Number of packets dropped in the last window
     * </pre>
     *
     * <code>uint32 packet_drop_count = 5;</code>
     * @return The packetDropCount.
     */
    int getPacketDropCount();

    /**
     * <pre>
     * An overarching health score defined by the node (0.0 to 1.0)
     * </pre>
     *
     * <code>float health_score = 6;</code>
     * @return The healthScore.
     */
    float getHealthScore();
  }
  /**
   * <pre>
   * Telemetry heartbeat sent by Torch nodes to coordinate optimal routing
   * </pre>
   *
   * Protobuf type {@code aether.proto.NodeTelemetry}
   */
  public static final class NodeTelemetry extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:aether.proto.NodeTelemetry)
      NodeTelemetryOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 1,
        /* suffix= */ "",
        "NodeTelemetry");
    }
    // Use NodeTelemetry.newBuilder() to construct.
    private NodeTelemetry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private NodeTelemetry() {
      nodeId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return aether.proto.Control.internal_static_aether_proto_NodeTelemetry_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return aether.proto.Control.internal_static_aether_proto_NodeTelemetry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return aether.proto.Control.internal_static_aether_proto_NodeTelemetry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              aether.proto.Control.NodeTelemetry.class, aether.proto.Control.NodeTelemetry.Builder.class);
    }

    public static final int NODE_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nodeId_ = "";
    /**
     * <code>string node_id = 1;</code>
     * @return The nodeId.
     */
    @java.lang.Override
    public java.lang.String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeId_ = s;
        return s;
      }
    }
    /**
     * <code>string node_id = 1;</code>
     * @return The bytes for nodeId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CPU_LOAD_PERCENT_FIELD_NUMBER = 2;
    private int cpuLoadPercent_ = 0;
    /**
     * <pre>
     * Load of the proxy node out of 100
     * </pre>
     *
     * <code>uint32 cpu_load_percent = 2;</code>
     * @return The cpuLoadPercent.
     */
    @java.lang.Override
    public int getCpuLoadPercent() {
      return cpuLoadPercent_;
    }

    public static final int BANDWIDTH_USAGE_MBPS_FIELD_NUMBER = 3;
    private float bandwidthUsageMbps_ = 0F;
    /**
     * <pre>
     * Total throughput currently being handled by node in Mbps
     * </pre>
     *
     * <code>float bandwidth_usage_mbps = 3;</code>
     * @return The bandwidthUsageMbps.
     */
    @java.lang.Override
    public float getBandwidthUsageMbps() {
      return bandwidthUsageMbps_;
    }

    public static final int LATENCY_MS_FIELD_NUMBER = 4;
    private float latencyMs_ = 0F;
    /**
     * <pre>
     * Local detected connection ping to backbone
     * </pre>
     *
     * <code>float latency_ms = 4;</code>
     * @return The latencyMs.
     */
    @java.lang.Override
    public float getLatencyMs() {
      return latencyMs_;
    }

    public static final int PACKET_DROP_COUNT_FIELD_NUMBER = 5;
    private int packetDropCount_ = 0;
    /**
     * <pre>
     * Number of packets dropped in the last window
     * </pre>
     *
     * <code>uint32 packet_drop_count = 5;</code>
     * @return The packetDropCount.
     */
    @java.lang.Override
    public int getPacketDropCount() {
      return packetDropCount_;
    }

    public static final int HEALTH_SCORE_FIELD_NUMBER = 6;
    private float healthScore_ = 0F;
    /**
     * <pre>
     * An overarching health score defined by the node (0.0 to 1.0)
     * </pre>
     *
     * <code>float health_score = 6;</code>
     * @return The healthScore.
     */
    @java.lang.Override
    public float getHealthScore() {
      return healthScore_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nodeId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, nodeId_);
      }
      if (cpuLoadPercent_ != 0) {
        output.writeUInt32(2, cpuLoadPercent_);
      }
      if (java.lang.Float.floatToRawIntBits(bandwidthUsageMbps_) != 0) {
        output.writeFloat(3, bandwidthUsageMbps_);
      }
      if (java.lang.Float.floatToRawIntBits(latencyMs_) != 0) {
        output.writeFloat(4, latencyMs_);
      }
      if (packetDropCount_ != 0) {
        output.writeUInt32(5, packetDropCount_);
      }
      if (java.lang.Float.floatToRawIntBits(healthScore_) != 0) {
        output.writeFloat(6, healthScore_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nodeId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, nodeId_);
      }
      if (cpuLoadPercent_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, cpuLoadPercent_);
      }
      if (java.lang.Float.floatToRawIntBits(bandwidthUsageMbps_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, bandwidthUsageMbps_);
      }
      if (java.lang.Float.floatToRawIntBits(latencyMs_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, latencyMs_);
      }
      if (packetDropCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, packetDropCount_);
      }
      if (java.lang.Float.floatToRawIntBits(healthScore_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, healthScore_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof aether.proto.Control.NodeTelemetry)) {
        return super.equals(obj);
      }
      aether.proto.Control.NodeTelemetry other = (aether.proto.Control.NodeTelemetry) obj;

      if (!getNodeId()
          .equals(other.getNodeId())) return false;
      if (getCpuLoadPercent()
          != other.getCpuLoadPercent()) return false;
      if (java.lang.Float.floatToIntBits(getBandwidthUsageMbps())
          != java.lang.Float.floatToIntBits(
              other.getBandwidthUsageMbps())) return false;
      if (java.lang.Float.floatToIntBits(getLatencyMs())
          != java.lang.Float.floatToIntBits(
              other.getLatencyMs())) return false;
      if (getPacketDropCount()
          != other.getPacketDropCount()) return false;
      if (java.lang.Float.floatToIntBits(getHealthScore())
          != java.lang.Float.floatToIntBits(
              other.getHealthScore())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NODE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getNodeId().hashCode();
      hash = (37 * hash) + CPU_LOAD_PERCENT_FIELD_NUMBER;
      hash = (53 * hash) + getCpuLoadPercent();
      hash = (37 * hash) + BANDWIDTH_USAGE_MBPS_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getBandwidthUsageMbps());
      hash = (37 * hash) + LATENCY_MS_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLatencyMs());
      hash = (37 * hash) + PACKET_DROP_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getPacketDropCount();
      hash = (37 * hash) + HEALTH_SCORE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getHealthScore());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static aether.proto.Control.NodeTelemetry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static aether.proto.Control.NodeTelemetry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static aether.proto.Control.NodeTelemetry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static aether.proto.Control.NodeTelemetry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static aether.proto.Control.NodeTelemetry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static aether.proto.Control.NodeTelemetry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static aether.proto.Control.NodeTelemetry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static aether.proto.Control.NodeTelemetry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static aether.proto.Control.NodeTelemetry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static aether.proto.Control.NodeTelemetry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static aether.proto.Control.NodeTelemetry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static aether.proto.Control.NodeTelemetry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(aether.proto.Control.NodeTelemetry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Telemetry heartbeat sent by Torch nodes to coordinate optimal routing
     * </pre>
     *
     * Protobuf type {@code aether.proto.NodeTelemetry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:aether.proto.NodeTelemetry)
        aether.proto.Control.NodeTelemetryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return aether.proto.Control.internal_static_aether_proto_NodeTelemetry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return aether.proto.Control.internal_static_aether_proto_NodeTelemetry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                aether.proto.Control.NodeTelemetry.class, aether.proto.Control.NodeTelemetry.Builder.class);
      }

      // Construct using aether.proto.Control.NodeTelemetry.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        nodeId_ = "";
        cpuLoadPercent_ = 0;
        bandwidthUsageMbps_ = 0F;
        latencyMs_ = 0F;
        packetDropCount_ = 0;
        healthScore_ = 0F;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return aether.proto.Control.internal_static_aether_proto_NodeTelemetry_descriptor;
      }

      @java.lang.Override
      public aether.proto.Control.NodeTelemetry getDefaultInstanceForType() {
        return aether.proto.Control.NodeTelemetry.getDefaultInstance();
      }

      @java.lang.Override
      public aether.proto.Control.NodeTelemetry build() {
        aether.proto.Control.NodeTelemetry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public aether.proto.Control.NodeTelemetry buildPartial() {
        aether.proto.Control.NodeTelemetry result = new aether.proto.Control.NodeTelemetry(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(aether.proto.Control.NodeTelemetry result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.nodeId_ = nodeId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.cpuLoadPercent_ = cpuLoadPercent_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.bandwidthUsageMbps_ = bandwidthUsageMbps_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.latencyMs_ = latencyMs_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.packetDropCount_ = packetDropCount_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.healthScore_ = healthScore_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof aether.proto.Control.NodeTelemetry) {
          return mergeFrom((aether.proto.Control.NodeTelemetry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(aether.proto.Control.NodeTelemetry other) {
        if (other == aether.proto.Control.NodeTelemetry.getDefaultInstance()) return this;
        if (!other.getNodeId().isEmpty()) {
          nodeId_ = other.nodeId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getCpuLoadPercent() != 0) {
          setCpuLoadPercent(other.getCpuLoadPercent());
        }
        if (java.lang.Float.floatToRawIntBits(other.getBandwidthUsageMbps()) != 0) {
          setBandwidthUsageMbps(other.getBandwidthUsageMbps());
        }
        if (java.lang.Float.floatToRawIntBits(other.getLatencyMs()) != 0) {
          setLatencyMs(other.getLatencyMs());
        }
        if (other.getPacketDropCount() != 0) {
          setPacketDropCount(other.getPacketDropCount());
        }
        if (java.lang.Float.floatToRawIntBits(other.getHealthScore()) != 0) {
          setHealthScore(other.getHealthScore());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                nodeId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                cpuLoadPercent_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 29: {
                bandwidthUsageMbps_ = input.readFloat();
                bitField0_ |= 0x00000004;
                break;
              } // case 29
              case 37: {
                latencyMs_ = input.readFloat();
                bitField0_ |= 0x00000008;
                break;
              } // case 37
              case 40: {
                packetDropCount_ = input.readUInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 53: {
                healthScore_ = input.readFloat();
                bitField0_ |= 0x00000020;
                break;
              } // case 53
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object nodeId_ = "";
      /**
       * <code>string node_id = 1;</code>
       * @return The nodeId.
       */
      public java.lang.String getNodeId() {
        java.lang.Object ref = nodeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nodeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string node_id = 1;</code>
       * @return The bytes for nodeId.
       */
      public com.google.protobuf.ByteString
          getNodeIdBytes() {
        java.lang.Object ref = nodeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string node_id = 1;</code>
       * @param value The nodeId to set.
       * @return This builder for chaining.
       */
      public Builder setNodeId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nodeId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string node_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNodeId() {
        nodeId_ = getDefaultInstance().getNodeId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string node_id = 1;</code>
       * @param value The bytes for nodeId to set.
       * @return This builder for chaining.
       */
      public Builder setNodeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nodeId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int cpuLoadPercent_ ;
      /**
       * <pre>
       * Load of the proxy node out of 100
       * </pre>
       *
       * <code>uint32 cpu_load_percent = 2;</code>
       * @return The cpuLoadPercent.
       */
      @java.lang.Override
      public int getCpuLoadPercent() {
        return cpuLoadPercent_;
      }
      /**
       * <pre>
       * Load of the proxy node out of 100
       * </pre>
       *
       * <code>uint32 cpu_load_percent = 2;</code>
       * @param value The cpuLoadPercent to set.
       * @return This builder for chaining.
       */
      public Builder setCpuLoadPercent(int value) {

        cpuLoadPercent_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Load of the proxy node out of 100
       * </pre>
       *
       * <code>uint32 cpu_load_percent = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCpuLoadPercent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cpuLoadPercent_ = 0;
        onChanged();
        return this;
      }

      private float bandwidthUsageMbps_ ;
      /**
       * <pre>
       * Total throughput currently being handled by node in Mbps
       * </pre>
       *
       * <code>float bandwidth_usage_mbps = 3;</code>
       * @return The bandwidthUsageMbps.
       */
      @java.lang.Override
      public float getBandwidthUsageMbps() {
        return bandwidthUsageMbps_;
      }
      /**
       * <pre>
       * Total throughput currently being handled by node in Mbps
       * </pre>
       *
       * <code>float bandwidth_usage_mbps = 3;</code>
       * @param value The bandwidthUsageMbps to set.
       * @return This builder for chaining.
       */
      public Builder setBandwidthUsageMbps(float value) {

        bandwidthUsageMbps_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Total throughput currently being handled by node in Mbps
       * </pre>
       *
       * <code>float bandwidth_usage_mbps = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBandwidthUsageMbps() {
        bitField0_ = (bitField0_ & ~0x00000004);
        bandwidthUsageMbps_ = 0F;
        onChanged();
        return this;
      }

      private float latencyMs_ ;
      /**
       * <pre>
       * Local detected connection ping to backbone
       * </pre>
       *
       * <code>float latency_ms = 4;</code>
       * @return The latencyMs.
       */
      @java.lang.Override
      public float getLatencyMs() {
        return latencyMs_;
      }
      /**
       * <pre>
       * Local detected connection ping to backbone
       * </pre>
       *
       * <code>float latency_ms = 4;</code>
       * @param value The latencyMs to set.
       * @return This builder for chaining.
       */
      public Builder setLatencyMs(float value) {

        latencyMs_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Local detected connection ping to backbone
       * </pre>
       *
       * <code>float latency_ms = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatencyMs() {
        bitField0_ = (bitField0_ & ~0x00000008);
        latencyMs_ = 0F;
        onChanged();
        return this;
      }

      private int packetDropCount_ ;
      /**
       * <pre>
       * Number of packets dropped in the last window
       * </pre>
       *
       * <code>uint32 packet_drop_count = 5;</code>
       * @return The packetDropCount.
       */
      @java.lang.Override
      public int getPacketDropCount() {
        return packetDropCount_;
      }
      /**
       * <pre>
       * Number of packets dropped in the last window
       * </pre>
       *
       * <code>uint32 packet_drop_count = 5;</code>
       * @param value The packetDropCount to set.
       * @return This builder for chaining.
       */
      public Builder setPacketDropCount(int value) {

        packetDropCount_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Number of packets dropped in the last window
       * </pre>
       *
       * <code>uint32 packet_drop_count = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPacketDropCount() {
        bitField0_ = (bitField0_ & ~0x00000010);
        packetDropCount_ = 0;
        onChanged();
        return this;
      }

      private float healthScore_ ;
      /**
       * <pre>
       * An overarching health score defined by the node (0.0 to 1.0)
       * </pre>
       *
       * <code>float health_score = 6;</code>
       * @return The healthScore.
       */
      @java.lang.Override
      public float getHealthScore() {
        return healthScore_;
      }
      /**
       * <pre>
       * An overarching health score defined by the node (0.0 to 1.0)
       * </pre>
       *
       * <code>float health_score = 6;</code>
       * @param value The healthScore to set.
       * @return This builder for chaining.
       */
      public Builder setHealthScore(float value) {

        healthScore_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * An overarching health score defined by the node (0.0 to 1.0)
       * </pre>
       *
       * <code>float health_score = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearHealthScore() {
        bitField0_ = (bitField0_ & ~0x00000020);
        healthScore_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:aether.proto.NodeTelemetry)
    }

    // @@protoc_insertion_point(class_scope:aether.proto.NodeTelemetry)
    private static final aether.proto.Control.NodeTelemetry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new aether.proto.Control.NodeTelemetry();
    }

    public static aether.proto.Control.NodeTelemetry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NodeTelemetry>
        PARSER = new com.google.protobuf.AbstractParser<NodeTelemetry>() {
      @java.lang.Override
      public NodeTelemetry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NodeTelemetry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NodeTelemetry> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public aether.proto.Control.NodeTelemetry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RouteDecisionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:aether.proto.RouteDecision)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Stream or Socket session ID
     * </pre>
     *
     * <code>string stream_id = 1;</code>
     * @return The streamId.
     */
    java.lang.String getStreamId();
    /**
     * <pre>
     * Stream or Socket session ID
     * </pre>
     *
     * <code>string stream_id = 1;</code>
     * @return The bytes for streamId.
     */
    com.google.protobuf.ByteString
        getStreamIdBytes();

    /**
     * <pre>
     * Target Proxy ID
     * </pre>
     *
     * <code>string selected_node_id = 2;</code>
     * @return The selectedNodeId.
     */
    java.lang.String getSelectedNodeId();
    /**
     * <pre>
     * Target Proxy ID
     * </pre>
     *
     * <code>string selected_node_id = 2;</code>
     * @return The bytes for selectedNodeId.
     */
    com.google.protobuf.ByteString
        getSelectedNodeIdBytes();

    /**
     * <pre>
     * ML Confidence in this route (0.0 to 1.0)
     * </pre>
     *
     * <code>float confidence_score = 3;</code>
     * @return The confidenceScore.
     */
    float getConfidenceScore();

    /**
     * <code>uint64 decision_timestamp_us = 4;</code>
     * @return The decisionTimestampUs.
     */
    long getDecisionTimestampUs();
  }
  /**
   * <pre>
   * Emitted by the ML router locally to re-assign traffic dynamically
   * </pre>
   *
   * Protobuf type {@code aether.proto.RouteDecision}
   */
  public static final class RouteDecision extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:aether.proto.RouteDecision)
      RouteDecisionOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 1,
        /* suffix= */ "",
        "RouteDecision");
    }
    // Use RouteDecision.newBuilder() to construct.
    private RouteDecision(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RouteDecision() {
      streamId_ = "";
      selectedNodeId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return aether.proto.Control.internal_static_aether_proto_RouteDecision_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return aether.proto.Control.internal_static_aether_proto_RouteDecision_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return aether.proto.Control.internal_static_aether_proto_RouteDecision_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              aether.proto.Control.RouteDecision.class, aether.proto.Control.RouteDecision.Builder.class);
    }

    public static final int STREAM_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object streamId_ = "";
    /**
     * <pre>
     * Stream or Socket session ID
     * </pre>
     *
     * <code>string stream_id = 1;</code>
     * @return The streamId.
     */
    @java.lang.Override
    public java.lang.String getStreamId() {
      java.lang.Object ref = streamId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        streamId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Stream or Socket session ID
     * </pre>
     *
     * <code>string stream_id = 1;</code>
     * @return The bytes for streamId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStreamIdBytes() {
      java.lang.Object ref = streamId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        streamId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SELECTED_NODE_ID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object selectedNodeId_ = "";
    /**
     * <pre>
     * Target Proxy ID
     * </pre>
     *
     * <code>string selected_node_id = 2;</code>
     * @return The selectedNodeId.
     */
    @java.lang.Override
    public java.lang.String getSelectedNodeId() {
      java.lang.Object ref = selectedNodeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        selectedNodeId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Target Proxy ID
     * </pre>
     *
     * <code>string selected_node_id = 2;</code>
     * @return The bytes for selectedNodeId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSelectedNodeIdBytes() {
      java.lang.Object ref = selectedNodeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        selectedNodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONFIDENCE_SCORE_FIELD_NUMBER = 3;
    private float confidenceScore_ = 0F;
    /**
     * <pre>
     * ML Confidence in this route (0.0 to 1.0)
     * </pre>
     *
     * <code>float confidence_score = 3;</code>
     * @return The confidenceScore.
     */
    @java.lang.Override
    public float getConfidenceScore() {
      return confidenceScore_;
    }

    public static final int DECISION_TIMESTAMP_US_FIELD_NUMBER = 4;
    private long decisionTimestampUs_ = 0L;
    /**
     * <code>uint64 decision_timestamp_us = 4;</code>
     * @return The decisionTimestampUs.
     */
    @java.lang.Override
    public long getDecisionTimestampUs() {
      return decisionTimestampUs_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(streamId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, streamId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(selectedNodeId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, selectedNodeId_);
      }
      if (java.lang.Float.floatToRawIntBits(confidenceScore_) != 0) {
        output.writeFloat(3, confidenceScore_);
      }
      if (decisionTimestampUs_ != 0L) {
        output.writeUInt64(4, decisionTimestampUs_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(streamId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, streamId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(selectedNodeId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, selectedNodeId_);
      }
      if (java.lang.Float.floatToRawIntBits(confidenceScore_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, confidenceScore_);
      }
      if (decisionTimestampUs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, decisionTimestampUs_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof aether.proto.Control.RouteDecision)) {
        return super.equals(obj);
      }
      aether.proto.Control.RouteDecision other = (aether.proto.Control.RouteDecision) obj;

      if (!getStreamId()
          .equals(other.getStreamId())) return false;
      if (!getSelectedNodeId()
          .equals(other.getSelectedNodeId())) return false;
      if (java.lang.Float.floatToIntBits(getConfidenceScore())
          != java.lang.Float.floatToIntBits(
              other.getConfidenceScore())) return false;
      if (getDecisionTimestampUs()
          != other.getDecisionTimestampUs()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STREAM_ID_FIELD_NUMBER;
      hash = (53 * hash) + getStreamId().hashCode();
      hash = (37 * hash) + SELECTED_NODE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSelectedNodeId().hashCode();
      hash = (37 * hash) + CONFIDENCE_SCORE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getConfidenceScore());
      hash = (37 * hash) + DECISION_TIMESTAMP_US_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDecisionTimestampUs());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static aether.proto.Control.RouteDecision parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static aether.proto.Control.RouteDecision parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static aether.proto.Control.RouteDecision parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static aether.proto.Control.RouteDecision parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static aether.proto.Control.RouteDecision parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static aether.proto.Control.RouteDecision parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static aether.proto.Control.RouteDecision parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static aether.proto.Control.RouteDecision parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static aether.proto.Control.RouteDecision parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static aether.proto.Control.RouteDecision parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static aether.proto.Control.RouteDecision parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static aether.proto.Control.RouteDecision parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(aether.proto.Control.RouteDecision prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Emitted by the ML router locally to re-assign traffic dynamically
     * </pre>
     *
     * Protobuf type {@code aether.proto.RouteDecision}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:aether.proto.RouteDecision)
        aether.proto.Control.RouteDecisionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return aether.proto.Control.internal_static_aether_proto_RouteDecision_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return aether.proto.Control.internal_static_aether_proto_RouteDecision_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                aether.proto.Control.RouteDecision.class, aether.proto.Control.RouteDecision.Builder.class);
      }

      // Construct using aether.proto.Control.RouteDecision.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        streamId_ = "";
        selectedNodeId_ = "";
        confidenceScore_ = 0F;
        decisionTimestampUs_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return aether.proto.Control.internal_static_aether_proto_RouteDecision_descriptor;
      }

      @java.lang.Override
      public aether.proto.Control.RouteDecision getDefaultInstanceForType() {
        return aether.proto.Control.RouteDecision.getDefaultInstance();
      }

      @java.lang.Override
      public aether.proto.Control.RouteDecision build() {
        aether.proto.Control.RouteDecision result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public aether.proto.Control.RouteDecision buildPartial() {
        aether.proto.Control.RouteDecision result = new aether.proto.Control.RouteDecision(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(aether.proto.Control.RouteDecision result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.streamId_ = streamId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.selectedNodeId_ = selectedNodeId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.confidenceScore_ = confidenceScore_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.decisionTimestampUs_ = decisionTimestampUs_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof aether.proto.Control.RouteDecision) {
          return mergeFrom((aether.proto.Control.RouteDecision)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(aether.proto.Control.RouteDecision other) {
        if (other == aether.proto.Control.RouteDecision.getDefaultInstance()) return this;
        if (!other.getStreamId().isEmpty()) {
          streamId_ = other.streamId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getSelectedNodeId().isEmpty()) {
          selectedNodeId_ = other.selectedNodeId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (java.lang.Float.floatToRawIntBits(other.getConfidenceScore()) != 0) {
          setConfidenceScore(other.getConfidenceScore());
        }
        if (other.getDecisionTimestampUs() != 0L) {
          setDecisionTimestampUs(other.getDecisionTimestampUs());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                streamId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                selectedNodeId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 29: {
                confidenceScore_ = input.readFloat();
                bitField0_ |= 0x00000004;
                break;
              } // case 29
              case 32: {
                decisionTimestampUs_ = input.readUInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object streamId_ = "";
      /**
       * <pre>
       * Stream or Socket session ID
       * </pre>
       *
       * <code>string stream_id = 1;</code>
       * @return The streamId.
       */
      public java.lang.String getStreamId() {
        java.lang.Object ref = streamId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          streamId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Stream or Socket session ID
       * </pre>
       *
       * <code>string stream_id = 1;</code>
       * @return The bytes for streamId.
       */
      public com.google.protobuf.ByteString
          getStreamIdBytes() {
        java.lang.Object ref = streamId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          streamId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Stream or Socket session ID
       * </pre>
       *
       * <code>string stream_id = 1;</code>
       * @param value The streamId to set.
       * @return This builder for chaining.
       */
      public Builder setStreamId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        streamId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Stream or Socket session ID
       * </pre>
       *
       * <code>string stream_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStreamId() {
        streamId_ = getDefaultInstance().getStreamId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Stream or Socket session ID
       * </pre>
       *
       * <code>string stream_id = 1;</code>
       * @param value The bytes for streamId to set.
       * @return This builder for chaining.
       */
      public Builder setStreamIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        streamId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object selectedNodeId_ = "";
      /**
       * <pre>
       * Target Proxy ID
       * </pre>
       *
       * <code>string selected_node_id = 2;</code>
       * @return The selectedNodeId.
       */
      public java.lang.String getSelectedNodeId() {
        java.lang.Object ref = selectedNodeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          selectedNodeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Target Proxy ID
       * </pre>
       *
       * <code>string selected_node_id = 2;</code>
       * @return The bytes for selectedNodeId.
       */
      public com.google.protobuf.ByteString
          getSelectedNodeIdBytes() {
        java.lang.Object ref = selectedNodeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          selectedNodeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Target Proxy ID
       * </pre>
       *
       * <code>string selected_node_id = 2;</code>
       * @param value The selectedNodeId to set.
       * @return This builder for chaining.
       */
      public Builder setSelectedNodeId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        selectedNodeId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Target Proxy ID
       * </pre>
       *
       * <code>string selected_node_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSelectedNodeId() {
        selectedNodeId_ = getDefaultInstance().getSelectedNodeId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Target Proxy ID
       * </pre>
       *
       * <code>string selected_node_id = 2;</code>
       * @param value The bytes for selectedNodeId to set.
       * @return This builder for chaining.
       */
      public Builder setSelectedNodeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        selectedNodeId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private float confidenceScore_ ;
      /**
       * <pre>
       * ML Confidence in this route (0.0 to 1.0)
       * </pre>
       *
       * <code>float confidence_score = 3;</code>
       * @return The confidenceScore.
       */
      @java.lang.Override
      public float getConfidenceScore() {
        return confidenceScore_;
      }
      /**
       * <pre>
       * ML Confidence in this route (0.0 to 1.0)
       * </pre>
       *
       * <code>float confidence_score = 3;</code>
       * @param value The confidenceScore to set.
       * @return This builder for chaining.
       */
      public Builder setConfidenceScore(float value) {

        confidenceScore_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ML Confidence in this route (0.0 to 1.0)
       * </pre>
       *
       * <code>float confidence_score = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearConfidenceScore() {
        bitField0_ = (bitField0_ & ~0x00000004);
        confidenceScore_ = 0F;
        onChanged();
        return this;
      }

      private long decisionTimestampUs_ ;
      /**
       * <code>uint64 decision_timestamp_us = 4;</code>
       * @return The decisionTimestampUs.
       */
      @java.lang.Override
      public long getDecisionTimestampUs() {
        return decisionTimestampUs_;
      }
      /**
       * <code>uint64 decision_timestamp_us = 4;</code>
       * @param value The decisionTimestampUs to set.
       * @return This builder for chaining.
       */
      public Builder setDecisionTimestampUs(long value) {

        decisionTimestampUs_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 decision_timestamp_us = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDecisionTimestampUs() {
        bitField0_ = (bitField0_ & ~0x00000008);
        decisionTimestampUs_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:aether.proto.RouteDecision)
    }

    // @@protoc_insertion_point(class_scope:aether.proto.RouteDecision)
    private static final aether.proto.Control.RouteDecision DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new aether.proto.Control.RouteDecision();
    }

    public static aether.proto.Control.RouteDecision getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RouteDecision>
        PARSER = new com.google.protobuf.AbstractParser<RouteDecision>() {
      @java.lang.Override
      public RouteDecision parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RouteDecision> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RouteDecision> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public aether.proto.Control.RouteDecision getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aether_proto_NodeTelemetry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_aether_proto_NodeTelemetry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aether_proto_RouteDecision_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_aether_proto_RouteDecision_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcontrol.proto\022\014aether.proto\"\235\001\n\rNodeTe" +
      "lemetry\022\017\n\007node_id\030\001 \001(\t\022\030\n\020cpu_load_per" +
      "cent\030\002 \001(\r\022\034\n\024bandwidth_usage_mbps\030\003 \001(\002" +
      "\022\022\n\nlatency_ms\030\004 \001(\002\022\031\n\021packet_drop_coun" +
      "t\030\005 \001(\r\022\024\n\014health_score\030\006 \001(\002\"u\n\rRouteDe" +
      "cision\022\021\n\tstream_id\030\001 \001(\t\022\030\n\020selected_no" +
      "de_id\030\002 \001(\t\022\030\n\020confidence_score\030\003 \001(\002\022\035\n" +
      "\025decision_timestamp_us\030\004 \001(\004b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_aether_proto_NodeTelemetry_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_aether_proto_NodeTelemetry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_aether_proto_NodeTelemetry_descriptor,
        new java.lang.String[] { "NodeId", "CpuLoadPercent", "BandwidthUsageMbps", "LatencyMs", "PacketDropCount", "HealthScore", });
    internal_static_aether_proto_RouteDecision_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_aether_proto_RouteDecision_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_aether_proto_RouteDecision_descriptor,
        new java.lang.String[] { "StreamId", "SelectedNodeId", "ConfidenceScore", "DecisionTimestampUs", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
