// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: packet.proto
// Protobuf Java Version: 4.34.1

package aether.proto;

@com.google.protobuf.Generated
public final class Packet extends com.google.protobuf.GeneratedFile {
  private Packet() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "Packet");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AetherPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:aether.proto.AetherPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Unique identifier of the origin client (Android device or desktop)
     * </pre>
     *
     * <code>string source_id = 1;</code>
     * @return The sourceId.
     */
    java.lang.String getSourceId();
    /**
     * <pre>
     * Unique identifier of the origin client (Android device or desktop)
     * </pre>
     *
     * <code>string source_id = 1;</code>
     * @return The bytes for sourceId.
     */
    com.google.protobuf.ByteString
        getSourceIdBytes();

    /**
     * <pre>
     * The target proxy node id this packet is destined for
     * </pre>
     *
     * <code>string target_id = 2;</code>
     * @return The targetId.
     */
    java.lang.String getTargetId();
    /**
     * <pre>
     * The target proxy node id this packet is destined for
     * </pre>
     *
     * <code>string target_id = 2;</code>
     * @return The bytes for targetId.
     */
    com.google.protobuf.ByteString
        getTargetIdBytes();

    /**
     * <pre>
     * For UDP-like reliability metrics: detect packet loss and reordering
     * </pre>
     *
     * <code>uint64 sequence_num = 3;</code>
     * @return The sequenceNum.
     */
    long getSequenceNum();

    /**
     * <pre>
     * Unix timestamp in microseconds
     * </pre>
     *
     * <code>uint64 timestamp_us = 4;</code>
     * @return The timestampUs.
     */
    long getTimestampUs();

    /**
     * <pre>
     * Type of traffic, determined by local ML or DPI (0=Unknown, 1=Streaming, 2=Gaming, 3=Background)
     * </pre>
     *
     * <code>uint32 traffic_class = 5;</code>
     * @return The trafficClass.
     */
    int getTrafficClass();

    /**
     * <pre>
     * Optional: Encryption IV (Initialization Vector) if payload is encrypted dynamically
     * </pre>
     *
     * <code>bytes cipher_iv = 6;</code>
     * @return The cipherIv.
     */
    com.google.protobuf.ByteString getCipherIv();

    /**
     * <pre>
     * The raw, encapsulated IP packet (TCP/UDP)
     * </pre>
     *
     * <code>bytes payload = 7;</code>
     * @return The payload.
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * <pre>
   * Used to wrap and transmit raw IP packets across the Torch proxy network.
   * </pre>
   *
   * Protobuf type {@code aether.proto.AetherPacket}
   */
  public static final class AetherPacket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:aether.proto.AetherPacket)
      AetherPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 1,
        /* suffix= */ "",
        "AetherPacket");
    }
    // Use AetherPacket.newBuilder() to construct.
    private AetherPacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private AetherPacket() {
      sourceId_ = "";
      targetId_ = "";
      cipherIv_ = com.google.protobuf.ByteString.EMPTY;
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return aether.proto.Packet.internal_static_aether_proto_AetherPacket_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return aether.proto.Packet.internal_static_aether_proto_AetherPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return aether.proto.Packet.internal_static_aether_proto_AetherPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              aether.proto.Packet.AetherPacket.class, aether.proto.Packet.AetherPacket.Builder.class);
    }

    public static final int SOURCE_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object sourceId_ = "";
    /**
     * <pre>
     * Unique identifier of the origin client (Android device or desktop)
     * </pre>
     *
     * <code>string source_id = 1;</code>
     * @return The sourceId.
     */
    @java.lang.Override
    public java.lang.String getSourceId() {
      java.lang.Object ref = sourceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Unique identifier of the origin client (Android device or desktop)
     * </pre>
     *
     * <code>string source_id = 1;</code>
     * @return The bytes for sourceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSourceIdBytes() {
      java.lang.Object ref = sourceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TARGET_ID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object targetId_ = "";
    /**
     * <pre>
     * The target proxy node id this packet is destined for
     * </pre>
     *
     * <code>string target_id = 2;</code>
     * @return The targetId.
     */
    @java.lang.Override
    public java.lang.String getTargetId() {
      java.lang.Object ref = targetId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The target proxy node id this packet is destined for
     * </pre>
     *
     * <code>string target_id = 2;</code>
     * @return The bytes for targetId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTargetIdBytes() {
      java.lang.Object ref = targetId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEQUENCE_NUM_FIELD_NUMBER = 3;
    private long sequenceNum_ = 0L;
    /**
     * <pre>
     * For UDP-like reliability metrics: detect packet loss and reordering
     * </pre>
     *
     * <code>uint64 sequence_num = 3;</code>
     * @return The sequenceNum.
     */
    @java.lang.Override
    public long getSequenceNum() {
      return sequenceNum_;
    }

    public static final int TIMESTAMP_US_FIELD_NUMBER = 4;
    private long timestampUs_ = 0L;
    /**
     * <pre>
     * Unix timestamp in microseconds
     * </pre>
     *
     * <code>uint64 timestamp_us = 4;</code>
     * @return The timestampUs.
     */
    @java.lang.Override
    public long getTimestampUs() {
      return timestampUs_;
    }

    public static final int TRAFFIC_CLASS_FIELD_NUMBER = 5;
    private int trafficClass_ = 0;
    /**
     * <pre>
     * Type of traffic, determined by local ML or DPI (0=Unknown, 1=Streaming, 2=Gaming, 3=Background)
     * </pre>
     *
     * <code>uint32 traffic_class = 5;</code>
     * @return The trafficClass.
     */
    @java.lang.Override
    public int getTrafficClass() {
      return trafficClass_;
    }

    public static final int CIPHER_IV_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString cipherIv_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Optional: Encryption IV (Initialization Vector) if payload is encrypted dynamically
     * </pre>
     *
     * <code>bytes cipher_iv = 6;</code>
     * @return The cipherIv.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getCipherIv() {
      return cipherIv_;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * The raw, encapsulated IP packet (TCP/UDP)
     * </pre>
     *
     * <code>bytes payload = 7;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sourceId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, sourceId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(targetId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, targetId_);
      }
      if (sequenceNum_ != 0L) {
        output.writeUInt64(3, sequenceNum_);
      }
      if (timestampUs_ != 0L) {
        output.writeUInt64(4, timestampUs_);
      }
      if (trafficClass_ != 0) {
        output.writeUInt32(5, trafficClass_);
      }
      if (!cipherIv_.isEmpty()) {
        output.writeBytes(6, cipherIv_);
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(7, payload_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sourceId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sourceId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(targetId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, targetId_);
      }
      if (sequenceNum_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, sequenceNum_);
      }
      if (timestampUs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, timestampUs_);
      }
      if (trafficClass_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, trafficClass_);
      }
      if (!cipherIv_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, cipherIv_);
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof aether.proto.Packet.AetherPacket)) {
        return super.equals(obj);
      }
      aether.proto.Packet.AetherPacket other = (aether.proto.Packet.AetherPacket) obj;

      if (!getSourceId()
          .equals(other.getSourceId())) return false;
      if (!getTargetId()
          .equals(other.getTargetId())) return false;
      if (getSequenceNum()
          != other.getSequenceNum()) return false;
      if (getTimestampUs()
          != other.getTimestampUs()) return false;
      if (getTrafficClass()
          != other.getTrafficClass()) return false;
      if (!getCipherIv()
          .equals(other.getCipherIv())) return false;
      if (!getPayload()
          .equals(other.getPayload())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SOURCE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSourceId().hashCode();
      hash = (37 * hash) + TARGET_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTargetId().hashCode();
      hash = (37 * hash) + SEQUENCE_NUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSequenceNum());
      hash = (37 * hash) + TIMESTAMP_US_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestampUs());
      hash = (37 * hash) + TRAFFIC_CLASS_FIELD_NUMBER;
      hash = (53 * hash) + getTrafficClass();
      hash = (37 * hash) + CIPHER_IV_FIELD_NUMBER;
      hash = (53 * hash) + getCipherIv().hashCode();
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static aether.proto.Packet.AetherPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static aether.proto.Packet.AetherPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static aether.proto.Packet.AetherPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static aether.proto.Packet.AetherPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static aether.proto.Packet.AetherPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static aether.proto.Packet.AetherPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static aether.proto.Packet.AetherPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static aether.proto.Packet.AetherPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static aether.proto.Packet.AetherPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static aether.proto.Packet.AetherPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static aether.proto.Packet.AetherPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static aether.proto.Packet.AetherPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(aether.proto.Packet.AetherPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Used to wrap and transmit raw IP packets across the Torch proxy network.
     * </pre>
     *
     * Protobuf type {@code aether.proto.AetherPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:aether.proto.AetherPacket)
        aether.proto.Packet.AetherPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return aether.proto.Packet.internal_static_aether_proto_AetherPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return aether.proto.Packet.internal_static_aether_proto_AetherPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                aether.proto.Packet.AetherPacket.class, aether.proto.Packet.AetherPacket.Builder.class);
      }

      // Construct using aether.proto.Packet.AetherPacket.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        sourceId_ = "";
        targetId_ = "";
        sequenceNum_ = 0L;
        timestampUs_ = 0L;
        trafficClass_ = 0;
        cipherIv_ = com.google.protobuf.ByteString.EMPTY;
        payload_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return aether.proto.Packet.internal_static_aether_proto_AetherPacket_descriptor;
      }

      @java.lang.Override
      public aether.proto.Packet.AetherPacket getDefaultInstanceForType() {
        return aether.proto.Packet.AetherPacket.getDefaultInstance();
      }

      @java.lang.Override
      public aether.proto.Packet.AetherPacket build() {
        aether.proto.Packet.AetherPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public aether.proto.Packet.AetherPacket buildPartial() {
        aether.proto.Packet.AetherPacket result = new aether.proto.Packet.AetherPacket(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(aether.proto.Packet.AetherPacket result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.sourceId_ = sourceId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.targetId_ = targetId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.sequenceNum_ = sequenceNum_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.timestampUs_ = timestampUs_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.trafficClass_ = trafficClass_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.cipherIv_ = cipherIv_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.payload_ = payload_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof aether.proto.Packet.AetherPacket) {
          return mergeFrom((aether.proto.Packet.AetherPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(aether.proto.Packet.AetherPacket other) {
        if (other == aether.proto.Packet.AetherPacket.getDefaultInstance()) return this;
        if (!other.getSourceId().isEmpty()) {
          sourceId_ = other.sourceId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getTargetId().isEmpty()) {
          targetId_ = other.targetId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getSequenceNum() != 0L) {
          setSequenceNum(other.getSequenceNum());
        }
        if (other.getTimestampUs() != 0L) {
          setTimestampUs(other.getTimestampUs());
        }
        if (other.getTrafficClass() != 0) {
          setTrafficClass(other.getTrafficClass());
        }
        if (!other.getCipherIv().isEmpty()) {
          setCipherIv(other.getCipherIv());
        }
        if (!other.getPayload().isEmpty()) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                sourceId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                targetId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                sequenceNum_ = input.readUInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                timestampUs_ = input.readUInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                trafficClass_ = input.readUInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                cipherIv_ = input.readBytes();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                payload_ = input.readBytes();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object sourceId_ = "";
      /**
       * <pre>
       * Unique identifier of the origin client (Android device or desktop)
       * </pre>
       *
       * <code>string source_id = 1;</code>
       * @return The sourceId.
       */
      public java.lang.String getSourceId() {
        java.lang.Object ref = sourceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sourceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Unique identifier of the origin client (Android device or desktop)
       * </pre>
       *
       * <code>string source_id = 1;</code>
       * @return The bytes for sourceId.
       */
      public com.google.protobuf.ByteString
          getSourceIdBytes() {
        java.lang.Object ref = sourceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Unique identifier of the origin client (Android device or desktop)
       * </pre>
       *
       * <code>string source_id = 1;</code>
       * @param value The sourceId to set.
       * @return This builder for chaining.
       */
      public Builder setSourceId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        sourceId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique identifier of the origin client (Android device or desktop)
       * </pre>
       *
       * <code>string source_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSourceId() {
        sourceId_ = getDefaultInstance().getSourceId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique identifier of the origin client (Android device or desktop)
       * </pre>
       *
       * <code>string source_id = 1;</code>
       * @param value The bytes for sourceId to set.
       * @return This builder for chaining.
       */
      public Builder setSourceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        sourceId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object targetId_ = "";
      /**
       * <pre>
       * The target proxy node id this packet is destined for
       * </pre>
       *
       * <code>string target_id = 2;</code>
       * @return The targetId.
       */
      public java.lang.String getTargetId() {
        java.lang.Object ref = targetId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          targetId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The target proxy node id this packet is destined for
       * </pre>
       *
       * <code>string target_id = 2;</code>
       * @return The bytes for targetId.
       */
      public com.google.protobuf.ByteString
          getTargetIdBytes() {
        java.lang.Object ref = targetId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targetId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The target proxy node id this packet is destined for
       * </pre>
       *
       * <code>string target_id = 2;</code>
       * @param value The targetId to set.
       * @return This builder for chaining.
       */
      public Builder setTargetId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        targetId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The target proxy node id this packet is destined for
       * </pre>
       *
       * <code>string target_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetId() {
        targetId_ = getDefaultInstance().getTargetId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The target proxy node id this packet is destined for
       * </pre>
       *
       * <code>string target_id = 2;</code>
       * @param value The bytes for targetId to set.
       * @return This builder for chaining.
       */
      public Builder setTargetIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        targetId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long sequenceNum_ ;
      /**
       * <pre>
       * For UDP-like reliability metrics: detect packet loss and reordering
       * </pre>
       *
       * <code>uint64 sequence_num = 3;</code>
       * @return The sequenceNum.
       */
      @java.lang.Override
      public long getSequenceNum() {
        return sequenceNum_;
      }
      /**
       * <pre>
       * For UDP-like reliability metrics: detect packet loss and reordering
       * </pre>
       *
       * <code>uint64 sequence_num = 3;</code>
       * @param value The sequenceNum to set.
       * @return This builder for chaining.
       */
      public Builder setSequenceNum(long value) {

        sequenceNum_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * For UDP-like reliability metrics: detect packet loss and reordering
       * </pre>
       *
       * <code>uint64 sequence_num = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSequenceNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sequenceNum_ = 0L;
        onChanged();
        return this;
      }

      private long timestampUs_ ;
      /**
       * <pre>
       * Unix timestamp in microseconds
       * </pre>
       *
       * <code>uint64 timestamp_us = 4;</code>
       * @return The timestampUs.
       */
      @java.lang.Override
      public long getTimestampUs() {
        return timestampUs_;
      }
      /**
       * <pre>
       * Unix timestamp in microseconds
       * </pre>
       *
       * <code>uint64 timestamp_us = 4;</code>
       * @param value The timestampUs to set.
       * @return This builder for chaining.
       */
      public Builder setTimestampUs(long value) {

        timestampUs_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unix timestamp in microseconds
       * </pre>
       *
       * <code>uint64 timestamp_us = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestampUs() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timestampUs_ = 0L;
        onChanged();
        return this;
      }

      private int trafficClass_ ;
      /**
       * <pre>
       * Type of traffic, determined by local ML or DPI (0=Unknown, 1=Streaming, 2=Gaming, 3=Background)
       * </pre>
       *
       * <code>uint32 traffic_class = 5;</code>
       * @return The trafficClass.
       */
      @java.lang.Override
      public int getTrafficClass() {
        return trafficClass_;
      }
      /**
       * <pre>
       * Type of traffic, determined by local ML or DPI (0=Unknown, 1=Streaming, 2=Gaming, 3=Background)
       * </pre>
       *
       * <code>uint32 traffic_class = 5;</code>
       * @param value The trafficClass to set.
       * @return This builder for chaining.
       */
      public Builder setTrafficClass(int value) {

        trafficClass_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Type of traffic, determined by local ML or DPI (0=Unknown, 1=Streaming, 2=Gaming, 3=Background)
       * </pre>
       *
       * <code>uint32 traffic_class = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTrafficClass() {
        bitField0_ = (bitField0_ & ~0x00000010);
        trafficClass_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString cipherIv_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Optional: Encryption IV (Initialization Vector) if payload is encrypted dynamically
       * </pre>
       *
       * <code>bytes cipher_iv = 6;</code>
       * @return The cipherIv.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getCipherIv() {
        return cipherIv_;
      }
      /**
       * <pre>
       * Optional: Encryption IV (Initialization Vector) if payload is encrypted dynamically
       * </pre>
       *
       * <code>bytes cipher_iv = 6;</code>
       * @param value The cipherIv to set.
       * @return This builder for chaining.
       */
      public Builder setCipherIv(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        cipherIv_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional: Encryption IV (Initialization Vector) if payload is encrypted dynamically
       * </pre>
       *
       * <code>bytes cipher_iv = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCipherIv() {
        bitField0_ = (bitField0_ & ~0x00000020);
        cipherIv_ = getDefaultInstance().getCipherIv();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * The raw, encapsulated IP packet (TCP/UDP)
       * </pre>
       *
       * <code>bytes payload = 7;</code>
       * @return The payload.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <pre>
       * The raw, encapsulated IP packet (TCP/UDP)
       * </pre>
       *
       * <code>bytes payload = 7;</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        payload_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The raw, encapsulated IP packet (TCP/UDP)
       * </pre>
       *
       * <code>bytes payload = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000040);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:aether.proto.AetherPacket)
    }

    // @@protoc_insertion_point(class_scope:aether.proto.AetherPacket)
    private static final aether.proto.Packet.AetherPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new aether.proto.Packet.AetherPacket();
    }

    public static aether.proto.Packet.AetherPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AetherPacket>
        PARSER = new com.google.protobuf.AbstractParser<AetherPacket>() {
      @java.lang.Override
      public AetherPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AetherPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AetherPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public aether.proto.Packet.AetherPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aether_proto_AetherPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_aether_proto_AetherPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014packet.proto\022\014aether.proto\"\233\001\n\014AetherP" +
      "acket\022\021\n\tsource_id\030\001 \001(\t\022\021\n\ttarget_id\030\002 " +
      "\001(\t\022\024\n\014sequence_num\030\003 \001(\004\022\024\n\014timestamp_u" +
      "s\030\004 \001(\004\022\025\n\rtraffic_class\030\005 \001(\r\022\021\n\tcipher" +
      "_iv\030\006 \001(\014\022\017\n\007payload\030\007 \001(\014b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_aether_proto_AetherPacket_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_aether_proto_AetherPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_aether_proto_AetherPacket_descriptor,
        new java.lang.String[] { "SourceId", "TargetId", "SequenceNum", "TimestampUs", "TrafficClass", "CipherIv", "Payload", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
